export default Languages = {
  ChatScreen: {
    HelloHowCanIHelpYou: {
      EN: "Hello, how can I help you?",
      HE: "שלום, איך אני יכול לעזור לך?",
      AR: "مرحبًا كيف يمكنني مساعدتك؟",
      ES: "Hola, ¿cómo puedo ayudarte?",
      RU: "Здравствуйте, чем я могу помочь вам?",
      FR: "Bonjour, comment puis-je vous aider?",
      POR: "Olá, como posso ajudá-lo?",
      CH: "你好，我可以帮你什么忙？",
      JP: "こんにちは、どのようにお手伝いできますか？",
    },
    Reception: {
      EN: "Reception",
      HE: "קבלה",
      AR: "استقبال",
      ES: "Recepción",
      RU: "Прием",
      FR: "Réception",
      POR: "Recepção",
      CH: "接待",
      JP: "受付",
    },
  },
  WelcomeScreen: {
    Start: {
      EN: "START",
      HE: "התחל",
      AR: "يبدأ",
      ES: "Comenzar",
      RU: "Начинать",
      FR: "Commencer",
      POR: "Começar",
      CH: "开始",
      JP: "始める",
    },
  },
  LoginScreen: {
    Welcome: {
      EN: "Welcome!",
      HE: "ברוכים הבאים!",
      AR: "اهلا وسهلا!",
      ES: "¡Bienvenido!",
      RU: "Добро пожаловать!",
      FR: "Accueillir!",
      POR: "Bem-vindo!",
      CH: "欢迎！",
      JP: "いらっしゃいませ！",
    },
    EnterYourEmailAndPassword: {
      EN: "Enter your email & password",
      HE: "הזן את האימייל והסיסמה שלך",
      AR: "أدخل بريدك الإلكتروني وكلمة المرور",
      ES: "Ingrese su correo electrónico y contraseña",
      RU: "Введите адрес электронной почты и пароль",
      FR: "Entrez votre e-mail et votre mot de passe",
      POR: "Digite seu e-mail e senha",
      CH: "输入您的电子邮件和密码",
      JP: "メールアドレスとパスワードを入力してください",
    },
    Email: {
      EN: "Email",
      HE: "דואר אלקטרוני",
      AR: "بريد إلكتروني",
      ES: "Correo electrónico",
      RU: "Электронная почта",
      FR: "E-mail",
      POR: "E-mail",
      CH: "电子邮件",
      JP: "Eメール",
    },
    Password: {
      EN: "Password",
      HE: "סיסמה",
      AR: "كلمة المرور",
      ES: "contraseña",
      RU: "пароль",
      FR: "mot de passe",
      POR: "senha",
      CH: "密码",
      JP: "パスワード",
    },
    Login: {
      EN: "Login",
      HE: "התחבר",
      AR: "تسجيل الدخول",
      ES: "acceso",
      RU: "авторизоваться",
      FR: "connexion",
      POR: "Conecte-se",
      CH: "登录",
      JP: "ログイン",
    },
    ForgotYourPassword: {
      EN: "Forgot your password?",
      HE: "שכחת את הסיסמה?",
      AR: "نسيت كلمة السر؟",
      ES: "¿Olvidaste tu contraseña?",
      RU: "Забыли пароль?",
      FR: "Mot de passe oublié?",
      POR: "Esqueceu sua senha?",
      CH: "忘记密码了吗？",
      JP: "パスワードをお忘れですか？",
    },
    OrCreateAnewAccount: {
      EN: "Or create a new account",
      HE: "או צור חשבון חדש",
      AR: "أو إنشاء حساب جديد",
      ES: "O crea una cuenta nueva",
      RU: "Или создайте новую учетную запись",
      FR: "Ou créer un nouveau compte",
      POR: "Ou crie uma nova conta",
      CH: "或创建一个新帐户",
      JP: "または、新しいアカウントを作成します",
    },
  },
  VerificationCodeComp: {
    EnterConfirmationCode: {
      EN: "Enter Confirmation Code",
      HE: "הכנס קוד אישור",
      AR: "أدخل رمز التأكيد",
      ES: "Introducir el código de confirmación",
      RU: "Введите код подтверждения",
      FR: "Entrez le code de confirmation",
      POR: "Introduza o código de confirmação",
      CH: "输入验证码",
      JP: "認証コードを入力",
    },
    A4DigitCodeWasSentTo: {
      EN: "A 4 Digit Code Was Sent To",
      HE: "קוד בן 4 ספרות נשלח אל",
      AR: "تم إرسال رمز مكون من 4 أرقام إلى",
      ES: "Se ha enviado un código de 4 dígitos a",
      RU: "Четырехзначный код был отправлен на",
      FR: "Un code à 4 chiffres a été envoyé à",
      POR: "Um código de 4 dígitos foi enviado para",
      CH: "一个 4 位数的代码已发送至",
      JP: "4桁のコードが送信されました",
    },
    ResendCode: {
      EN: "Resend code",
      HE: "שלח קוד שוב",
      AR: "أعد إرسال الرمز",
      ES: "Reenviar codigo",
      RU: "Отправить код еще раз",
      FR: "Renvoyer le code",
      POR: "Reenviar código",
      CH: "重新发送验证码",
      JP: "コードを再送する",
    },
    Continue: {
      EN: "Continue",
      HE: "המשך",
      AR: "استمر",
      ES: "Continuar",
      RU: "Продолжить",
      FR: "Continuer",
      POR: "Continuar",
      CH: "继续",
      JP: "続ける",
    },
  },
  ResetPasswordComp: {
    PasswordReset: {
      EN: "Password Reset",
      HE: "איפוס סיסמה",
      AR: "إعادة تعيين كلمة المرور",
      ES: "Restablecimiento de contraseña",
      RU: "Восстановление пароля",
      FR: "Réinitialisation du mot de passe",
      POR: "Redefinição de senha",
      CH: "重设密码",
      JP: "パスワードのリセット",
    },
    ChooseNewPassword: {
      EN: "Choose A New Password",
      HE: "בחר סיסמא חדשה",
      AR: "اختر كلمة مرور جديدة",
      ES: "Elija una Nueva Contraseña",
      RU: "Выберите новый пароль",
      FR: "Choisissez un nouveau mot de passe",
      POR: "Escolha uma nova senha",
      CH: "选择一个新密码",
      JP: "新しいパスワードを選択してください",
    },
    NewPassword: {
      EN: "New Password",
      HE: "סיסמא חדשה",
      AR: "كلمة مرور جديدة",
      ES: "Nueva Contraseña",
      RU: "Новый пароль",
      FR: "Nouveau mot de passe",
      POR: "Nova senha",
      CH: "新密码",
      JP: "新しいパスワード",
    },
    ConfirmNewPassword: {
      EN: "Confirm New Password",
      HE: "אמת סיסמא חדשה",
      AR: "تأكيد كلمة المرور الجديدة",
      ES: "Confirmar Nueva Contraseña",
      RU: "Подтвердите новый пароль",
      FR: "Confirmer le Nouveau Mot de Passe",
      POR: "Confirmar Nova Senha",
      CH: "确认新密码",
      JP: "新しいパスワードの確認",
    },
    Continue: {
      EN: "Continue",
      HE: "המשך",
      AR: "استمر",
      ES: "Continuar",
      RU: "Продолжить",
      FR: "Continuer",
      POR: "Continuar",
      CH: "继续",
      JP: "続ける",
    },
    PasswordsDoNotMatch: {
      EN: "Passwords do not match",
      HE: "סיסמאות לא תואמות",
      AR: "كلمات المرور غير متطابقة",
      ES: "Las contraseñas no coinciden",
      RU: "Пароли не совпадают",
      FR: "Les mots de passe ne correspondent pas",
      POR: "As senhas não coincidem",
      CH: "密码不一致",
      JP: "パスワードが一致しません",
    },
  },
  GetEmailComp: {
    EmailVerification: {
      EN: "Email Verification",
      HE: 'אימות הדוא"ל',
      AR: "تأكيد بواسطة البريد الالكتروني",
      ES: "verificacion de email",
      RU: "Подтверждение по элетронной почте",
      FR: "vérification de l'E-mail",
      POR: "verificação de e-mail",
      CH: "电子邮件验证",
      JP: "メール認証",
    },
    EnterYourEmail: {
      EN: "Enter your email address",
      HE: 'הזן את כתובת הדוא"ל שלך',
      AR: "أدخل عنوان بريدك الالكتروني",
      ES: "Ingrese su dirección de correo electrónico",
      RU: "Введите ваш адрес электронной почты",
      FR: "Entrez votre adresse email",
      POR: "Insira o seu endereço de email",
      CH: "输入你的电子邮箱地址",
      JP: "メールアドレスを入力してください",
    },
    Email: {
      EN: "Email",
      HE: "דואר אלקטרוני",
      AR: "بريد إلكتروني",
      ES: "Correo electrónico",
      RU: "Электронная почта",
      FR: "E-mail",
      POR: "E-mail",
      CH: "电子邮件",
      JP: "Eメール",
    },
    Continue: {
      EN: "Continue",
      HE: "המשך",
      AR: "استمر",
      ES: "Continuar",
      RU: "Продолжить",
      FR: "Continuer",
      POR: "Continuar",
      CH: "继续",
      JP: "続ける",
    },
  },
  CreateUserScreen: {
    CreateAccount: {
      EN: "Create Account",
      HE: "צור חשבון",
      AR: "إنشاء حساب",
      ES: "Crear una cuenta",
      RU: "Зарегистрироваться",
      FR: "Créer un compte",
      POR: "Criar uma conta",
      CH: "创建账户",
      JP: "アカウントを作成する",
    },
    Email: {
      EN: "Email",
      HE: "דואר אלקטרוני",
      AR: "بريد إلكتروني",
      ES: "Correo electrónico",
      RU: "Электронная почта",
      FR: "E-mail",
      POR: "E-mail",
      CH: "电子邮件",
      JP: "Eメール",
    },
    NewPassword: {
      EN: "New Password",
      HE: "סיסמא חדשה",
      AR: "كلمة مرور جديدة",
      ES: "Nueva Contraseña",
      RU: "Новый пароль",
      FR: "Nouveau mot de passe",
      POR: "Nova senha",
      CH: "新密码",
      JP: "新しいパスワード",
    },
    ConfirmNewPassword: {
      EN: "Confirm New Password",
      HE: "אמת סיסמא חדשה",
      AR: "تأكيد كلمة المرور الجديدة",
      ES: "Confirmar Nueva Contraseña",
      RU: "Подтвердите новый пароль",
      FR: "Confirmer le Nouveau Mot de Passe",
      POR: "Confirmar Nova Senha",
      CH: "确认新密码",
      JP: "新しいパスワードの確認",
    },
    SelectLanguage: {
      EN: "Select Language",
      HE: "בחר שפה",
      AR: "اختار اللغة",
      ES: "seleccione el idioma",
      RU: "выберите язык",
      FR: "Choisir la langue",
      POR: "selecione o idioma",
      CH: "选择语言",
      JP: "言語を選択する",
    },
  },
  GetPersonalInfoComp: {
    CreateAccount: {
      EN: "Create Account",
      HE: "צור חשבון",
      AR: "إنشاء حساب",
      ES: "Crear una cuenta",
      RU: "Зарегистрироваться",
      FR: "Créer un compte",
      POR: "Criar uma conta",
      CH: "创建账户",
      JP: "アカウントを作成する",
    },
    PersonalInfo: {
      EN: "Personal Info",
      HE: "פרטים אישיים",
      AR: "معلومات شخصية",
      ES: "Información Personal",
      RU: "Личная информация",
      FR: "Informations personnelles",
      POR: "Informações pessoais",
      CH: "个人信息",
      JP: "個人情報",
    },
    FirstName: {
      EN: "First Name",
      HE: "שם פרטי",
      AR: "الاسم الأول",
      ES: "Nombre",
      RU: "Имя",
      FR: "Prénom",
      POR: "Primeiro nome",
      CH: "名字",
      JP: "名",
    },
    LastName: {
      EN: "Last Name",
      HE: "שם משפחה",
      AR: "الاسم الأخير",
      ES: "Apellido",
      RU: "Фамилия",
      FR: "Nom de famille",
      POR: "Sobrenome",
      CH: "姓氏",
      JP: "姓",
    },
    PhoneNumber: {
      EN: "Phone Number",
      HE: "מספר טלפון",
      AR: "رقم الهاتف",
      ES: "Número de teléfono",
      RU: "Номер телефона",
      FR: "Numéro de téléphone",
      POR: "Número de telefone",
      CH: "电话号码",
      JP: "電話番号",
    },
    BirthDate: {
      EN: "Birthday",
      HE: "תאריך לידה",
      AR: "عيد ميلاد",
      ES: "Cumpleaños",
      RU: "День рождения",
      FR: "Anniversaire",
      POR: "Aniversário",
      CH: "出生日期",
      JP: "誕生日",
    },
    Gender: {
      EN: "Gender",
      HE: "מגדר",
      AR: "الجنس",
      ES: "Género",
      RU: "Пол",
      FR: "Genre",
      POR: "Gênero",
      CH: "性别",
      JP: "性別",
    },
    Male: {
      EN: "Male",
      HE: "זכר",
      AR: "ذكر",
      ES: "Masculino",
      RU: "Мужской",
      FR: "Masculin",
      POR: "Masculino",
      CH: "男性",
      JP: "男性",
    },
    Female: {
      EN: "Female",
      HE: "נקבה",
      AR: "أنثى",
      ES: "Femenino",
      RU: "Женский",
      FR: "Féminin",
      POR: "Feminino",
      CH: "女性",
      JP: "女性",
    },
    Continue: {
      EN: "Continue",
      HE: "המשך",
      AR: "استمر",
      ES: "Continuar",
      RU: "Продолжить",
      FR: "Continuer",
      POR: "Continuar",
      CH: "继续",
      JP: "続ける",
    },
  },
  GetLoginInfoComp: {
    CreateAccount: {
      EN: "Create Account",
      HE: "צור חשבון",
      AR: "إنشاء حساب",
      ES: "Crear una cuenta",
      RU: "Зарегистрироваться",
      FR: "Créer un compte",
      POR: "Criar uma conta",
      CH: "创建账户",
      JP: "アカウントを作成する",
    },
    LoginInformation: {
      EN: "Login Information",
      HE: "פרטי כניסה",
      AR: "معلومات الدخول",
      ES: "Información de Inicio de Sesión",
      RU: "Информация для входа",
      FR: "Informations de Connexion",
      POR: "Informações de Login",
      CH: "登录信息",
      JP: "ログイン情報",
    },
    Email: {
      EN: "Email",
      HE: "דואר אלקטרוני",
      AR: "بريد إلكتروني",
      ES: "Correo electrónico",
      RU: "Электронная почта",
      FR: "E-mail",
      POR: "E-mail",
      CH: "电子邮件",
      JP: "Eメール",
    },
    NewPassword: {
      EN: "New Password",
      HE: "סיסמא חדשה",
      AR: "كلمة مرور جديدة",
      ES: "Nueva Contraseña",
      RU: "Новый пароль",
      FR: "Nouveau mot de passe",
      POR: "Nova senha",
      CH: "新密码",
      JP: "新しいパスワード",
    },
    ConfirmNewPassword: {
      EN: "Confirm New Password",
      HE: "אמת סיסמא חדשה",
      AR: "تأكيد كلمة المرور الجديدة",
      ES: "Confirmar Nueva Contraseña",
      RU: "Подтвердите новый пароль",
      FR: "Confirmer le Nouveau Mot de Passe",
      POR: "Confirmar Nova Senha",
      CH: "确认新密码",
      JP: "新しいパスワードの確認",
    },
    PasswordsDoNotMatch: {
      EN: "Passwords do not match",
      HE: "סיסמאות לא תואמות",
      AR: "كلمات المرور غير متطابقة",
      ES: "Las contraseñas no coinciden",
      RU: "Пароли не совпадают",
      FR: "Les mots de passe ne correspondent pas",
      POR: "As senhas não coincidem",
      CH: "密码不一致",
      JP: "パスワードが一致しません",
    },
  },
  PersonalPageScreen: {
    MyPage: {
      EN: "My page",
      HE: "העמוד שלי",
      AR: "صفحتي",
      ES: "Mi página",
      RU: "Моя страницаа",
      FR: "Ma page",
      POR: "Minha página",
      CH: "我的页面",
      JP: "マイページ",
    },
    CheckIn: {
      EN: "Check-In",
      HE: "צ'ק אין",
      AR: "تحقق في",
      ES: "Registrarse",
      RU: "Регистрироваться",
      FR: "Enregistrement",
      POR: "Check-in",
      CH: "报到",
      JP: "チェックイン",
    },
    CheckOut: {
      EN: "Check-Out",
      HE: "צ'ק אאוט",
      AR: "الدفع",
      ES: "Verificar",
      RU: "Выезд",
      FR: "Vérifier",
      POR: "Confira",
      CH: "查看",
      JP: "チェックアウト",
    },
    HouseHold: {
      EN: "Household",
      HE: "משק בית",
      AR: "أُسرَة",
      ES: "Familiar",
      RU: "Семья",
      FR: "Ménage",
      POR: "Doméstico",
      CH: "家庭",
      JP: "家庭",
    },
    RoomCleaningSchedule: {
      EN: "Room cleaning schedule",
      HE: "לוח זמנים לניקיון חדרים",
      AR: "جدول تنظيف الغرفة",
      ES: "Horario de limpieza de habitaciones",
      RU: "График уборки номера",
      FR: "Horaire de nettoyage des chambres",
      POR: "Horário de limpeza do quarto",
      CH: "房间清洁时间表",
      JP: "ルームクリーニングスケジュール",
    },
    NewRequest: {
      EN: "New Request",
      HE: "בקשה חדשה",
      AR: "طلب جديد",
      ES: "Nueva solicitud",
      RU: "Новый запрос",
      FR: "Nouvelle requête",
      POR: "Novo pedido",
      CH: "新请求",
      JP: "新しいリクエスト",
    },
    HotelNavigation: {
      EN: "Hotel Navigation",
      HE: "ניווט למלון",
      AR: "تنقلات الفندق",
      ES: "Navegación del hotel",
      RU: "Навигация по отелю",
      FR: "Navigation de l'hôtel",
      POR: "Navegação do hotel",
      CH: "酒店导航",
      JP: "ホテルナビゲーション",
    },
  },
  SpaTreatmenScreen: {
    MassageTreatments: {
      EN: "MASSAGE TREATMENTS",
      HE: "טיפולי ספא",
      AR: "علاجات التدليك",
      ES: "TRATAMIENTOS DE MASAJE",
      RU: "МАССАЖНЫЕ ПРОЦЕДУРЫ",
      FR: "SOINS DE MASSAGE",
      POR: "TRATAMENTOS DE MASSAGEM",
      CH: "按摩护理",
      JP: "マッサージトリートメント",
    },
    TypeHere: {
      EN: "Type here",
      HE: "הקלד פה",
      AR: "أكتب هنا",
      ES: "Escriba aquí",
      RU: "Введите здесь",
      FR: "Écrivez ici",
      POR: "Digite aqui",
      CH: "在此输入",
      JP: "ここに入力",
    },
    SwedishMassage: {
      EN: "Swedish Massage",
      HE: "עיסוי שוודי",
      AR: "التدليك السويدية",
      ES: "Masaje sueco",
      RU: "Шведский массаж",
      FR: "Massage Suédois",
      POR: "Massagem sueca",
      CH: "瑞典式按摩",
      JP: "スウェディッシュマッサージ",
    },
    HotStoneMassage: {
      EN: "Hot Stone Massage",
      HE: "עיסוי אבנים חמות",
      AR: "تدليك الحجر الساخن",
      ES: "Masaje con piedras calientes",
      RU: "Массаж горячими камнями",
      FR: "Massage aux pierres chaudes",
      POR: "Massagem com pedras quentes",
      CH: "热石按摩",
      JP: "ホットストーンマッサージ",
    },
    CombinedMassage: {
      EN: "Combined Massage",
      HE: "עיסוי משולב",
      AR: "التدليك المشترك",
      ES: "Masaje Combinado",
      RU: "Комбинированный массаж",
      FR: "Massage Combiné",
      POR: "Massagem Combinada",
      CH: "组合按摩",
      JP: "複合マッサージ",
    },
    DeepTissuMassage: {
      EN: "Deep Tissue Massage",
      HE: "עיסוי רקמות עמוק",
      AR: "تدليك الأنسجة العميقة",
      ES: "Masaje de tejido profundo",
      RU: "Глубокий массаж тканей",
      FR: "Massage des tissus profonds",
      POR: "Massagem de tecidos profundos",
      CH: "深层组织按摩",
      JP: "ディープティッシュマッサージ",
    },
    PrenatalMassage: {
      EN: "Prenatal Massage",
      HE: "עיסוי טרום לידה",
      AR: "تدليك ما قبل الولادة",
      ES: "Masaje Prenatal",
      RU: "пренатальный массаж",
      FR: "Massage prénatal",
      POR: "Massagem pré-natal",
      CH: "产前按摩",
      JP: "産前マッサージ",
    },
  },
  CardScreen: {
    Description: {
      EN: "Description:",
      HE: ":תיאור",
      AR: ":وصف",
      ES: "Descripción:",
      RU: "Описание:",
      FR: "Description:",
      POR: "Descrição:",
      CH: "描述:",
      JP: "説明:",
    },
    OpeningHours: {
      EN: "Opening Hours:",
      HE: ":שעות פתיחה",
      AR: ":ساعات العمل",
      ES: "Horario de apertura:",
      RU: "Часы работы:",
      FR: "Horaires d'ouvertures:",
      POR: "Horário de Funcionamento:",
      CH: "营业时间:",
      JP: "営業時間:",
    },
    Rating: {
      EN: "Rating",
      HE: "דירוג",
      AR: "تقييم",
      ES: "Valoración",
      RU: "Рейтинг",
      FR: "Évaluation",
      POR: "Avaliação",
      CH: "评级",
      JP: "評価",
    },
    Address: {
      EN: "Address:",
      HE: ":כתובת",
      AR: ":عنوان",
      ES: "DIRECCIÓN:",
      RU: "Адрес:",
      FR: "Adresse:",
      POR: "Endereço:",
      CH: "地址:",
      JP: "住所:",
    },
    Phone: {
      EN: "Phone:",
      HE: ":טלפון",
      AR: ":هاتف",
      ES: "Teléfono:",
      RU: "Телефон:",
      FR: "Téléphone:",
      POR: "Telefone:",
      CH: "电话:",
      JP: "電話:",
    },
    Price: {
      EN: "Price",
      HE: "מחיר",
      AR: "السعر",
      ES: "Precio",
      RU: "Цена",
      FR: "Prix",
      POR: "Preço",
      CH: "价格",
      JP: "価格",
    },
    BasePrice: {
      EN: "Base Price",
      HE: "מחיר בסיס",
      AR: "السعر الأساسي",
      ES: "Precio base",
      RU: "Базовая цена",
      FR: "Prix de base",
      POR: "Preço base",
      CH: "基础价格",
      JP: "ベース価格",
    },
    PriceForAdditional15Minutes: {
      EN: "Price for Additional 15 Minutes",
      HE: "מחיר למשך 15 דקות נוספות",
      AR: "السعر لمدة 15 دقيقة إضافية",
      ES: "Precio por 15 minutos adicionales",
      RU: "Цена за дополнительные 15 минут",
      FR: "Prix pour 15 minutes supplémentaires",
      POR: "Preço por 15 minutos adicionais",
      CH: "额外15分钟的价格",
      JP: "追加15分間の価格",
    },
    HallNum: {
      EN: "Hall Number",
      HE: "מספר אולם",
      AR: "رقم القاعةة",
      ES: "Número del Salón",
      RU: "Номер зала",
      FR: "Numéro de salle",
      POR: "Número do Salão",
      CH: "大厅编号",
      JP: "ホール番号",
    },
    FREE: {
      EN: "FREE",
      HE: "חינם",
      AR: "حر",
      ES: "GRATIS",
      RU: "БЕСПЛАТНО",
      FR: "GRATUIT",
      POR: "LIVRE",
      CH: "自由的",
      JP: "無料",
    },
    PickThis: {
      EN: "Pick this",
      HE: "בחר זאת",
      AR: "اختر هذا",
      ES: "Elije esto",
      RU: "Выбери это",
      FR: "Choisissez ceci",
      POR: "Escolha isso",
      CH: "选择这个",
      JP: "これを選んでください ",
    },
    Menu: {
      EN: "Menu",
      HE: "תפריט",
      AR: "قائمة ",
      ES: "Menú",
      RU: "Меню",
      FR: "Menu",
      POR: "Menu",
      CH: "菜单",
      JP: "メニュー",
    },
  },
  ConciergeActivitiesScreen: {
    RecommendedActivitiesInTheArea: {
      EN: "Recommended activities in the area",
      HE: "מקומות מומלצים באזור",
      AR: "الأنشطة الموصى بها في المنطقة",
      ES: "Actividades recomendadas en la zona",
      RU: "Рекомендуемые мероприятия в этом районе",
      FR: "Activités recommandées dans la région",
      POR: "Atividades recomendadas na área",
      CH: "该地区的推荐活动",
      JP: "周辺のおすすめアクティビティ",
    },
  },
  ConciergeMainScreen: {
    QuestionnaireRecommendations: {
      EN: "Questionnaire recommendations",
      HE: "שאלון המלצות",
      AR: "توصيات الاستبيان",
      ES: "Recomendaciones del cuestionario",
      RU: "Рекомендации по анкете",
      FR: "Recommandations du questionnaire",
      POR: "Recomendações do questionário",
      CH: "问卷建议",
      JP: "アンケートの推奨事項",
    },
    TopRatedActivities: {
      EN: "Top Rated Activities",
      HE: "פעילויות בעלות הדירוג הגבוה ביותר",
      AR: "أفضل الأنشطة تقييمًا",
      ES: "Actividades mejor valoradas",
      RU: "Лучшие оцененные мероприятия",
      FR: "Activités les mieux notées",
      POR: "Atividades mais bem avaliadas",
      CH: "最受欢迎的活动",
      JP: "トップ評価のアクティビティ",
    },
    Questionnaire: {
      EN: "Questionnaire",
      HE: "שאלון",
      AR: "استبيان",
      ES: "Cuestionario",
      RU: "Опросник",
      FR: "Questionnaire",
      POR: "Questionário",
      CH: "问卷",
      JP: "アンケート",
    },
    More: {
      EN: "More",
      HE: "לעוד",
      AR: "أكثر",
      ES: "Más",
      RU: "Более",
      FR: "Plus",
      POR: "Mais",
      CH: "更多的",
      JP: "もっと",
    },
    WithoutLeavingTheHotel: {
      EN: "Without leaving the hotel",
      HE: "בלי לצאת מהמלון",
      AR: "بدون مغادرة الفندق",
      ES: "Sin salir del hotel",
      RU: "Не выходя из отеля",
      FR: "Sans quitter l'hôtel",
      POR: "Sem sair do hotel",
      CH: "无需离开酒店",
      JP: "ホテルを出ることなく",
    },
    RecommendedPlacesToVisit: {
      EN: "Recommended places to visit",
      HE: "מקומות מומלצים לביקור",
      AR: "الأماكن الموصى بها للزيارة",
      ES: "Lugares recomendados para visitar",
      RU: "Рекомендуемые места для посещения",
      FR: "Endroits recommandés à visiter",
      POR: "Lugares recomendados para visitar",
      CH: "推荐景点",
      JP: "おすすめスポット",
    },
  },
  FeedbackScreen: {
    Feedback: {
      EN: "Feedback",
      HE: "מָשׁוֹב",
      AR: "تعليق",
      ES: "Comentario",
      RU: "Обратная связь",
      FR: "Retour",
      POR: "Opinião",
      CH: "反馈",
      JP: "フィードバック",
    },
    DidYouEnjoyTheActivity: {
      EN: "Did you enjoy the activity?",
      HE: "?נהניתם מהפעילות",
      AR: "هل استمتعت بالنشاط؟",
      ES: "¿Te gustó la actividad?",
      RU: "Вам понравилось занятие?",
      FR: "Avez-vous apprécié l'activité?",
      POR: "Gostou da atividade?",
      CH: "你喜欢这个活动吗？",
      JP: "アクティビティは楽しかったですか？",
    },
    WasTheActivityAGoodFitForYourPersonality: {
      EN: "Was the activity a good fit for your personality?",
      HE: "?האם הפעילות התאימה לאישיותך",
      AR: "هل كان النشاط مناسبًا لشخصيتك؟",
      ES: "¿La actividad se adecuaba bien a su personalidad?",
      RU: "Соответствовала ли эта деятельность вашей личности?",
      FR: "L'activité correspondait-elle à votre personnalité?",
      POR: "A atividade foi adequada para sua personalidade?",
      CH: "该活动是否适合您的个性？",
      JP: "その活動はあなたの性格にぴったりでしたか？",
    },
    AnythingElse: {
      EN: "Anything else?",
      HE: "?עוד משהו",
      AR: "أي شيء آخر؟",
      ES: "¿Algo más?",
      RU: "Что-нибудь еще?",
      FR: "Rien d'autre?",
      POR: "Algo mais?",
      CH: "还要别的吗?",
      JP: "他に何か？",
    },
  },
  HealthDeclarationScreen: {
    HealthDeclarationForm: {
      EN: "Health declaration form",
      HE: "טופס הצהרת בריאות",
      AR: "استمارة البيان الصحي",
      ES: "Formulario de declaración de salud",
      RU: "Форма декларации здоровья",
      FR: "Formulaire de déclaration de santé",
      POR: "formulário de declaração de saúde",
      CH: "健康申报表",
      JP: "健康申告書",
    },
    DoYouHaveAnyOfTheFollowingConditions: {
      EN: "Do you have any of the following conditions?",
      HE: "?האם יש לך אחד מהתנאים הבאים",
      AR: "هل لديك أي من الشروط التالية؟",
      ES: "¿Tiene alguna de las siguientes condiciones?",
      RU: "Есть ли у вас какие-либо из следующих условий?",
      FR: "Avez-vous l'une des conditions suivantes?",
      POR: "Você tem alguma das seguintes condições?",
      CH: "您是否具备以下条件?",
      JP: "次のような条件はありませんか?",
    },
    FullName: {
      EN: "Full Name",
      HE: "שם מלא",
      AR: "الاسم الكامل",
      ES: "Nombre completo",
      RU: "Полное имя",
      FR: "Nom complet",
      POR: "Nome completo",
      CH: "全名",
      JP: "フルネーム",
    },
    NEXT: {
      EN: "NEXT",
      HE: "הבא",
      AR: "التالي",
      ES: "SIGUIENTE",
      RU: "СЛЕДУЮЩИЙ ",
      FR: "SUIVANT",
      POR: "PRÓXIMO",
      CH: "下一个",
      JP: "次へ",
    },
  },
  HomeScreen: {
    PerfectForYou: {
      EN: "Perfect for you",
      HE: "מושלם בשבילך",
      AR: "المثالي بالنسبة لك",
      ES: "Perfecto para ti",
      RU: "Идеально подходит для вас",
      FR: "Parfait pour toi",
      POR: "Perfeito para você",
      CH: "非常适合你",
      JP: "あなたにぴったり",
    },
    ToTheConcierge: {
      EN: "To the concierge",
      HE: "לקונסיירז'",
      AR: "إلى البواب",
      ES: "al conserje",
      RU: "Консьержу",
      FR: "A la conciergerie",
      POR: "Para o porteiro",
      CH: "前往礼宾部",
      JP: "コンシェルジュへ",
    },
    SpaTime: {
      EN: "Spa time",
      HE: "זמן לספא",
      AR: "وقت السبا",
      ES: "tiempo de spa",
      RU: "Спа время",
      FR: "Temps de spa",
      POR: "tempo de spa",
      CH: "水疗时间",
      JP: "スパタイム",
    },
    MoreSpaTreatments: {
      EN: "More spa treatments",
      HE: "טיפולי ספא נוספים",
      AR: "المزيد من علاجات السبا",
      ES: "Más tratamientos de spa",
      RU: "Еще спа-процедуры",
      FR: "Plus de cures thermales",
      POR: "Mais tratamentos de spa",
      CH: "更多水疗护理",
      JP: "その他のスパ トリートメント",
    },
    RoomService: {
      EN: "Room Service",
      HE: "שירות חדרים",
      AR: "خدمة الغرفة",
      ES: "Servicio de Habitación",
      RU: "Обслуживание в номере",
      FR: "Service en Chambre",
      POR: "Serviço de Quarto",
      CH: "客房服务",
      JP: "ルームサービス",
    },
    ToTheFullMenu: {
      EN: "To the full menu",
      HE: "לתפריט המלא",
      AR: "إلى القائمة الكاملة",
      ES: "Al menú completo",
      RU: "К полному меню",
      FR: "Vers le menu complet",
      POR: "Para o menu completo",
      CH: "查看完整菜单",
      JP: "全メニューへ",
    },
    HotelFacilities: {
      EN: "Hotel facilities",
      HE: "מתקני המלון",
      AR: "مرافق الفندق",
      ES: "Precio total",
      RU: "Общая цена",
      FR: "Prix total",
      POR: "Preço total",
      CH: "总价",
      JP: "合計金額",
    },
  },
  HotelActivitieScreen: {
    WithoutLeavingTheHotel: {
      EN: "Without leaving the hotel",
      HE: "בלי לצאת מהמלון",
      AR: "بدون مغادرة الفندق",
      ES: "Sin salir del hotel",
      RU: "Не выходя из отеля",
      FR: "Sans quitter l'hôtel",
      POR: "Sem sair do hotel",
      CH: "无需离开酒店",
      JP: "ホテルを出ることなく",
    },
  },
  MainScreen: {
    SomethingToSnack: {
      EN: "Something to snack",
      HE: "משהו לנשנש",
      AR: "شيء لتناول وجبة خفيفة",
      ES: "algo para picar",
      RU: "Что-нибудь перекусить",
      FR: "Quelque chose à grignoter",
      POR: "Algo para lanche",
      CH: "吃点东西",
      JP: "おやつに何か",
    },
  },
  SpaConfirmationScreen: {
    YOUR: {
      EN: "YOUR",
      HE: "שֶׁלְךָ",
      AR: "لك",
      ES: "SU",
      RU: "ТВОЙ",
      FR: "TON",
      POR: "SEU",
      CH: "你的",
      JP: "あなたの",
    },
    MASSAGE: {
      EN: "MASSAGE",
      HE: "'מסאז",
      AR: "تدليك",
      ES: "MASAJE",
      RU: "МАССАЖ",
      FR: "MASSAGE",
      POR: "MASSAGEM",
      CH: "按摩",
      JP: "マッサージ",
    },
    TREATMENT: {
      EN: "TREATMENT",
      HE: "טיפול",
      AR: "علاج",
      ES: "TRATAMIENTO",
      RU: "УХОД",
      FR: "TRAITEMENT",
      POR: "TRATAMENTO",
      CH: "治疗",
      JP: "処理",
    },
    OrderDetails: {
      EN: "Order Details",
      HE: "פרטי הזמנה",
      AR: "تفاصيل الطلب",
      ES: "Detalles del pedido",
      RU: "Информация для заказа",
      FR: "détails de la commande",
      POR: "detalhes do pedido",
      CH: "订单详细信息",
      JP: "注文詳細",
    },
    Duration: {
      EN: "Duration:",
      HE: ":משך זמן",
      AR: "المدة الزمنية:",
      ES: "Duración:",
      RU: "Продолжительность:",
      FR: "Durée:",
      POR: "Tempo de duração:",
      CH: "持续时间：",
      JP: "所要時間:",
    },
    minutes: {
      EN: "minutes",
      HE: "דקות",
      AR: "دقائق",
      ES: "minutos",
      RU: "минуты",
      FR: "minutes",
      POR: "minutos",
      CH: "分钟",
      JP: "分",
    },
    Gender: {
      EN: "Gender:",
      HE: ":מגדר",
      AR: "جنس:",
      ES: "género:",
      RU: "гендер:",
      FR: "genre:",
      POR: "género:",
      CH: "性别:",
      JP: "ジェンダ:",
    },
    CoupleMassage: {
      EN: "Couple massage",
      HE: "מסאז' זוגי",
      AR: "مساج للزوجين",
      ES: "Masaje de pareja",
      RU: "Парный массаж",
      FR: "Massage en couple",
      POR: "Massagem para casal",
      CH: "双人按摩 ",
      JP: "カップルマッサージ ",
    },
    SingleMassage: {
      EN: "Single massage",
      HE: "מסאז' יחיד",
      AR: "مساج فردي",
      ES: "Masaje individual",
      RU: "Одиночный массаж",
      FR: "Massage individuel",
      POR: "Massagem individual",
      CH: "单人按摩",
      JP: "シングルマッサージ ",
    },
    Date: {
      EN: "Date:",
      HE: ":תאריך",
      AR: "تاريخ :",
      ES: "Dátil:",
      RU: "Финик:",
      FR: "Datte:",
      POR: "Tâmara:",
      CH: "枣:",
      JP: "デーツ:",
    },
    Hour: {
      EN: "Hour:",
      HE: ":שעה",
      AR: "ساعة:",
      ES: "Hora:",
      RU: "Час:",
      FR: "Heure:",
      POR: "Hora:",
      CH: "小时:",
      JP: "時間:",
    },
    Price: {
      EN: "Price:",
      HE: ":מחיר",
      AR: "سعر:",
      ES: "Precio:",
      RU: "Цена:",
      FR: "Prix:",
      POR: "Preço:",
      CH: "价格:",
      JP: "価格:",
    },
    TherapistGender: {
      EN: "Therapist gender:",
      HE: ":מגדר המטפל",
      AR: "جنس المعالِج:",
      ES: "Género del terapeuta:",
      RU: "Пол терапевта:",
      FR: "Genre du thérapeute:",
      POR: "Gênero do terapeuta:",
      CH: "治疗师性别:",
      JP: "セラピストの性別:",
    },
    Therapist1Gender: {
      EN: "Therapist 1 gender:",
      HE: ":מגדר המטפל הראשון",
      AR: "جنس المعالِج 1:",
      ES: "Género del terapeuta 1:",
      RU: "Пол терапевта 1:",
      FR: "Genre du thérapeute 1:",
      POR: "Gênero do terapeuta 1:",
      CH: "治疗师1性别:",
      JP: "セラピスト1の性別:",
    },
    Therapist2Gender: {
      EN: "Therapist 1 gender:",
      HE: ":מגדר המטפל השני",
      AR: "جنس المعالِج 2:",
      ES: "Género del terapeuta 2:",
      RU: "Пол терапевта 2:",
      FR: "Genre du thérapeute 2:",
      POR: "Gênero do terapeuta 2:",
      CH: "治疗师2性别:",
      JP: "セラピスト2の性別:",
    },
    Confirm: {
      EN: "Confirm",
      HE: "אשר",
      AR: "تأكيد",
      ES: "Confirmar",
      RU: "Подтвердить",
      FR: "Confirmer",
      POR: "Confirmar",
      CH: "确认",
      JP: "確認する",
    },
    Cancel: {
      EN: "Cancel",
      HE: "בטל",
      AR: "إلغاء",
      ES: "Cancelar",
      RU: "Отменить",
      FR: "Annuler",
      POR: "Cancelar",
      CH: "取消",
      JP: "キャンセルする",
    },
  },
  SpaMainScreen: {
    Spa: {
      EN: "Spa",
      HE: "ספא",
      AR: "منتجع صحي",
      ES: "Spa",
      RU: "спа",
      FR: "Spa",
      POR: "spa",
      CH: "温泉",
      JP: "スパ",
    },
    MassageTreatments: {
      EN: "MASSAGE TREATMENTS",
      HE: "טיפולי ספא",
      AR: "علاجات التدليك",
      ES: "TRATAMIENTOS DE MASAJE",
      RU: "МАССАЖНЫЕ ПРОЦЕДУРЫ",
      FR: "SOINS DE MASSAGE",
      POR: "TRATAMENTOS DE MASSAGEM",
      CH: "按摩护理",
      JP: "マッサージトリートメント",
    },
    ForMoreTreatments: {
      EN: "For more treatments",
      HE: "לטיפולים נוספים",
      AR: "للمزيد من العلاجات",
      ES: "Para más tratamientos",
      RU: "Для большего количества процедур",
      FR: "Pour plus de traitements",
      POR: "Para mais tratamentos",
      CH: "更多治疗",
      JP: "その他の治療について",
    },
    TheSpaFacilities: {
      EN: "The spa facilities",
      HE: "מתקני הספא",
      AR: "مرافق السبا",
      ES: "las instalaciones del balneario",
      RU: "Спа-услуги",
      FR: "Les installations thermales",
      POR: "As instalações do spa",
      CH: "水疗设施",
      JP: "スパ施設",
    },
  },
  NewCheckInScreen: {
    ContactlessCheckIn: {
      EN: "Contactless Check-In",
      HE: "צ'ק אין ללא מגע",
      AR: "تسجيل الوصول بدون تلامس",
      ES: "Facturación sin contacto",
      RU: "Бесконтактная регистрация",
      FR: "Enregistrement sans contact",
      POR: "Check-in sem contato",
      CH: "非接触式登记入住",
      JP: "非接触チェックイン",
    },
    PleaseReviewYourReservation: {
      EN: "Please review your reservation",
      HE: "אנא בדוק את ההזמנה שלך",
      AR: "يرجى مراجعة الحجز الخاص بك",
      ES: "Por favor revise su reserva",
      RU: "Пожалуйста, проверьте ваше бронирование",
      FR: "Veuillez vérifier votre réservation",
      POR: "Revise sua reserva",
      CH: "请检查您的预订",
      JP: "ご予約をご確認ください",
    },
    Name: {
      EN: "Name",
      HE: "שם",
      AR: "اسم",
      ES: "Nombre",
      RU: "Имя",
      FR: "Nom",
      POR: "Nome",
      CH: "姓名",
      JP: "名前",
    },
    CheckIn: {
      EN: "Check-in",
      HE: "צ'ק אין",
      AR: "تحقق في",
      ES: "Registrarse",
      RU: "Регистрироваться",
      FR: "Регистрироваться",
      POR: "Check-in",
      CH: "报到",
      JP: "チェックイン",
    },
    CheckOut: {
      EN: "Check-out",
      HE: "צ'ק אאוט",
      AR: "الدفع",
      ES: "Verificar",
      RU: "Проверить",
      FR: "Vérifier",
      POR: "Confira",
      CH: "查看",
      JP: "チェックアウト",
    },
    EstimatedTotal: {
      EN: "Estimated Total",
      HE: 'סה"כ משוער',
      AR: "المجموع التقديري",
      ES: "Total Estimado",
      RU: "Расчетная сумма",
      FR: "Total estimé",
      POR: "Total Estimado",
      CH: "估计总数",
      JP: "推定合計",
    },
    Next: {
      EN: "Next",
      HE: "הבא",
      AR: "التالي",
      ES: "Próximo",
      RU: "Следующий",
      FR: "Suivant",
      POR: "Próximo",
      CH: "下一个",
      JP: "次",
    },
  },
  ConciergeCard: {
    Call: {
      EN: "Call",
      HE: "להתקשר",
      AR: "يتصل",
      ES: "Llamar",
      RU: "Вызов",
      FR: "Appel",
      POR: "Chamar",
      CH: "称呼",
      JP: "電話",
    },
  },
  HotelActivityCard: {
    SignMeUp: {
      EN: "Sign me up",
      HE: "רשום אותי",
      AR: "أشركني",
      ES: "Inscríbeme",
      RU: "Запишите меня",
      FR: "Enregistre-moi",
      POR: "Inscreva-me",
      CH: "注册我",
      JP: "サインアップ",
    },
  },
  HotelActivityCarouselCard: {
    SignMeUp: {
      EN: "Sign me up",
      HE: "רשום אותי",
      AR: "أشركني",
      ES: "Inscríbeme",
      RU: "Запишите меня",
      FR: "Enregistre-moi",
      POR: "Inscreva-me",
      CH: "注册我",
      JP: "サインアップ",
    },
    FREE: {
      EN: "FREE",
      HE: "חינם",
      AR: "حر",
      ES: "GRATIS",
      RU: "БЕСПЛАТНО",
      FR: "GRATUIT",
      POR: "LIVRE",
      CH: "自由的",
      JP: "無料",
    },
  },
  HotelNavigationScreen: {
    Address: {
      EN: "Address:",
      HE: "כתובת:",
      AR: "العنوان:",
      ES: "Dirección:",
      RU: "Адрес:",
      FR: "Adresse :",
      POR: "Endereço:",
      CH: "地址：",
      JP: "住所：",
    },
    Phone: {
      EN: "Phone:",
      HE: "טלפון:",
      AR: "الهاتف:",
      ES: "Teléfono:",
      RU: "Телефон:",
      FR: "Téléphone :",
      POR: "Telefone:",
      CH: "电话：",
      JP: "電話：",
    },
    Navigate: {
      EN: "Navigate",
      HE: "נווט",
      AR: "توجه",
      ES: "Navegar",
      RU: "Навигация",
      FR: "Naviguer",
      POR: "Navegar",
      CH: "导航",
      JP: "ナビゲート",
    },
    AlwaysHere: {
      EN: "Always here",
      HE: "תמיד כאן",
      AR: "هنا دائمًا",
      ES: "Siempre aquí",
      RU: "Всегда здесь",
      FR: "Toujours ici",
      POR: "Sempre aqui",
      CH: "始终在这里",
      JP: "常にここに",
    },
  },
  RoomServiceMenu: {
    Price: {
      EN: "Price",
      HE: "מחיר",
      AR: "السعر",
      ES: "Precio",
      RU: "Цена",
      FR: "Prix",
      POR: "Preço",
      CH: "价格",
      JP: "価格",
    },
    AddToCart: {
      EN: "Add to cart:",
      HE: ":הוסף לעגלה",
      AR: "أضف إلى السلة:",
      ES: "Añadir al carrito:",
      RU: "Добавить в корзину:",
      FR: "Ajouter au panier:",
      POR: "Adicionar ao carrinho:",
      CH: "添加到购物车:",
      JP: "カートに追加:",
    },
    Food: {
      EN: "Food",
      HE: "אוכל",
      AR: "طعام",
      ES: "Comida",
      RU: "Еда",
      FR: "Nourriture",
      POR: "Comida",
      CH: "食物",
      JP: "食べ物",
    },
    Cart: {
      EN: "Cart",
      HE: "עגלה",
      AR: "عربة ",
      ES: "Carro",
      RU: "Корзина",
      FR: "Chariot",
      POR: "Carrinho",
      CH: "购物车",
      JP: "カート",
    },
    YourShoppingCart: {
      EN: "Your shopping cart",
      HE: "עגלת הקניות שלך",
      AR: "عربة التسوق الخاصة بك",
      ES: "Tu carrito de compras",
      RU: "Ваша корзина покупок",
      FR: "Votre panier d'achat",
      POR: "Seu carrinho de compras",
      CH: "您的购物车",
      JP: "あなたのショッピングカート",
    },
    TotalPrice: {
      EN: "Total Price:",
      HE: ":מחיר כולל",
      AR: "السعر الإجمالي:",
      ES: "Precio total:",
      RU: "Общая цена:",
      FR: "Prix total:",
      POR: "Preço total:",
      CH: "总价:",
      JP: "合計金額:",
    },
  },
  RoomServiceMenuNew: {
    RoomService: {
      EN: "Room Service",
      HE: "שירות חדרים",
      AR: "خدمة الغرف",
      ES: "Servicio de habitaciones",
      RU: "Обслуживание в номере",
      FR: "Service en chambre",
      POR: "Serviço de quarto",
      CH: "客房服务",
      JP: "ルームサービス",
    },
    Cart: {
      EN: "Cart",
      HE: "עגלה",
      AR: "عربة ",
      ES: "Carro",
      RU: "Корзина",
      FR: "Chariot",
      POR: "Carrinho",
      CH: "购物车",
      JP: "カート",
    },
    WeApologizeWeDontHaveThatAmount: {
      EN: "We apologize, we don't have that amount!",
      HE: "!אנו מתנצלים, אין לנו את הכמות הזו",
      AR: "نحن نعتذر، ليس لدينا تلك الكمية!",
      ES: "Nos disculpamos, ¡no tenemos esa cantidad!",
      RU: "Мы извиняемся, у нас нет такого количества!",
      FR: "Nous nous excusons, nous n'avons pas cette quantité!",
      POR: "Pedimos desculpas, não temos essa quantidade!",
      CH: "我们很抱歉，我们没有那么多数量!",
      JP: "申し訳ありませんが、その数量はありません!",
    },
    Food: {
      EN: "Food",
      HE: "אוכל",
      AR: "طعام",
      ES: "Comida",
      RU: "Еда",
      FR: "Nourriture",
      POR: "Comida",
      CH: "食物",
      JP: "食べ物",
    },
    Drinks: {
      EN: "Drinks",
      HE: "משקאות",
      AR: "مشروبات",
      ES: "Bebidas",
      RU: "Напитки",
      FR: "Boissons",
      POR: "Bebidas",
      CH: "饮料",
      JP: "飲み物",
    },
    Alcohol: {
      EN: "Alcohol",
      HE: "אלכוהול",
      AR: "كحول",
      ES: "Alcohol",
      RU: "Алкоголь ",
      FR: "Alcool",
      POR: "Álcool",
      CH: "酒精",
      JP: "アルコール",
    },
    More: {
      EN: "More",
      HE: "לעוד",
      AR: "أكثر",
      ES: "Más",
      RU: "Более",
      FR: "Plus",
      POR: "Mais",
      CH: "更多的",
      JP: "もっと",
    },
    ColdDrinks: {
      EN: "Cold Drinks",
      HE: "משקאות קרים",
      AR: "مشروبات باردة",
      ES: "Bebidas frías",
      RU: "Холодные напитки ",
      FR: "Boissons froides",
      POR: "Bebidas geladas",
      CH: "冷饮",
      JP: "冷たい飲み物",
    },
    HotDrinks: {
      EN: "Hot Drinks",
      HE: "משקאות חמים",
      AR: "مشروبات ساخنة",
      ES: "Bebidas calientes",
      RU: "Горячие напитки",
      FR: "Boissons chaudes",
      POR: "Bebidas quentes",
      CH: "热饮",
      JP: "熱い飲み物",
    },
    Cocktails: {
      EN: "Cocktails",
      HE: "קוקטיילים",
      AR: "كوكتيلات",
      ES: "Cócteles",
      RU: "Коктейли",
      FR: "Cocktails",
      POR: "Coquetéis",
      CH: "鸡尾酒",
      JP: "カクテル",
    },
    Wine: {
      EN: "Wine",
      HE: "יין",
      AR: "نبيذ",
      ES: "Vino",
      RU: "Вино",
      FR: "Vin",
      POR: "Vinho",
      CH: "葡萄酒",
      JP: "ワイン",
    },
  },
  RoomCleaningScreen: {
    CleaningSchedule: {
      EN: "Cleaning schedule",
      HE: "תזמון ניקיון",
      AR: "جدول التنظيف",
      ES: "Horario de limpieza",
      RU: "График уборки",
      FR: "Programme de nettoyage",
      POR: "Cronograma de limpeza",
      CH: "清洁计划",
      JP: "掃除スケジュール",
    },
    RequestedCleaningSchedule: {
      EN: "Requested Cleaning Schedule",
      HE: "תוכנית ניקיון מבוקשת",
      AR: "جدول التنظيف المطلوب",
      ES: "Horario de Limpieza Solicitado",
      RU: "Запрошенное расписание уборки",
      FR: "Horaire de Nettoyage Demandé",
      POR: "Cronograma de Limpeza Solicitado",
      CH: "要求的清洁计划",
      JP: "依頼された清掃スケジュール",
    },
    Date: {
      EN: "Date:",
      HE: ":תאריך",
      AR: "تاريخ :",
      ES: "Dátil:",
      RU: "Финик:",
      FR: "Datte:",
      POR: "Tâmara:",
      CH: "枣:",
      JP: "デーツ:",
    },
    Hour: {
      EN: "Hour:",
      HE: ":שעה",
      AR: "ساعة:",
      ES: "Hora:",
      RU: "Час:",
      FR: "Heure:",
      POR: "Hora:",
      CH: "小时:",
      JP: "時間:",
    },
    WeWillNotCleanYouRoomAsRequested: {
      EN: "We will not clean you room as requested",
      HE: "לא ננקה את החדר שלך כפי שביקשת",
      AR: "لن نقوم بتنظيف غرفتك كما طلبت",
      ES: "No limpiaremos tu habitación como lo solicitaste",
      RU: "Мы не будем убирать вашу комнату, как вы просили",
      FR: "Nous ne nettoierons pas votre chambre comme demandé",
      POR: "Não iremos limpar seu quarto conforme solicitado",
      CH: " 我们不会按照您的要求打扫您的房间",
      JP: "ご要望に沿って部屋を掃除しないでしょう",
    },
    CleaningScheduleForTommorow: {
      EN: "Cleaning schedule for tommorow",
      HE: "תזמון ניקיון למחר",
      AR: "جدول التنظيف للغد",
      ES: "Horario de limpieza para mañana",
      RU: "График уборки на завтра",
      FR: "Programme de nettoyage pour demain",
      POR: "Cronograma de limpeza para amanhã",
      CH: "明天的清洁计划",
      JP: "明日の清掃スケジュール",
    },
    Hour2: {
      EN: "Hour",
      HE: "שעה",
      AR: "ساعة",
      ES: "Hora",
      RU: "Час",
      FR: "Heure",
      POR: "Hora",
      CH: "小时",
      JP: "時間",
    },
    Minute: {
      EN: "minutes",
      HE: "דקות",
      AR: "دقائق",
      ES: "minutos",
      RU: "минуты",
      FR: "minutes",
      POR: "minutos",
      CH: "分钟",
      JP: "分",
    },
    DoNotCleanMyRoom: {
      EN: "Do not clean my room",
      HE: "אל תנקו את החדר שלי",
      AR: "لا تنظف غرفتي",
      ES: "No limpies mi habitación",
      RU: "Не убирайте мою комнату",
      FR: "Ne nettoyez pas ma chambre",
      POR: "Não limpe o meu quarto",
      CH: "不要打扫我的房间",
      JP: "私の部屋を掃除しないでください",
    },
    Continue: {
      EN: "Continue",
      HE: "המשך",
      AR: "استمر",
      ES: "Continuar",
      RU: "Продолжить",
      FR: "Continuer",
      POR: "Continuar",
      CH: "继续",
      JP: "続ける",
    },
  },
  PaymentScreen: {
    ChooseAPaymentMethod: {
      EN: "Choose a payment method",
      HE: "בחר אמצעי תשלום",
      AR: "اختر طريقة الدفع",
      ES: "Elija un método de pago",
      RU: "Выберите способ оплаты",
      FR: "Choisissez un mode de paiement",
      POR: "Escolha um método de pagamento",
      CH: "选择付款方式",
      JP: "支払い方法を選択してください",
    },
    YouWontBeChargedUntilYouClickThePaymentButton: {
      EN: "You won't be charged until you click the payment button",
      HE: "לא תחוייב עד שתלחץ על כפתור התשלום",
      AR: "لن يتم خصم أموالك حتى تنقر على زر الدفع",
      ES: "No se le cobrará hasta que haga clic en el botón de pago",
      RU: "Вам не будет начислено платежей до нажатия кнопки оплаты",
      FR: "Vous ne serez pas débité avant de cliquer sur le bouton de paiement",
      POR: "Você não será cobrado até clicar no botão de pagamento",
      CH: "在点击支付按钮之前，您不会被收费",
      JP: "支払いボタンをクリックするまで請求はありません",
    },
    CreditCard: {
      EN: "Credit Card",
      HE: "כרטיס אשראי",
      AR: "بطاقة الائتمان",
      ES: "Tarjeta de crédito",
      RU: "Кредитная карта",
      FR: "Carte de crédit",
      POR: "Cartão de crédito",
      CH: "信用卡",
      JP: "クレジットカード",
    },
    ApplePay: {
      EN: "Apple Pay",
      HE: "אפל פיי",
      AR: "ابل باي",
      ES: "Apel Pei",
      RU: "Эпл Пей",
      FR: "Apel Pei",
      POR: "Apl Pei",
      CH: "苹果支付",
      JP: "アップルペイ",
    },
    Pay: {
      EN: "Pay",
      HE: "שלם",
      AR: "دفع",
      ES: "Pagar",
      RU: "Оплата",
      FR: "Payer",
      POR: "Pagar",
      CH: "支付",
      JP: "支払い",
    },
    Payment: {
      EN: "Payment",
      HE: "תשלום",
      AR: "الدفع",
      ES: "Pago",
      RU: "Оплата",
      FR: "Paiement",
      POR: "Pagamento",
      CH: "付款",
      JP: "支払い",
    },
    ContinueWithPayment: {
      EN: "Continue with the payment?",
      HE: "האם להמשיך עם התשלום?",
      AR: "الاستمرار في الدفع؟",
      ES: "¿Continuar con el pago?",
      RU: "Продолжить оплату?",
      FR: "Continuer avec le paiement?",
      POR: "Continuar com o pagamento?",
      CH: "继续付款？",
      JP: "支払いを続けますか？",
    },
    Yes: {
      EN: "Yes",
      HE: "כן",
      AR: "نعم",
      ES: "Sí",
      RU: "Да",
      FR: "Oui",
      POR: "Sim",
      CH: "是",
      JP: "はい",
    },
    No: {
      EN: "No",
      HE: "לא",
      AR: "لا",
      ES: "No",
      RU: "Нет",
      FR: "Non",
      POR: "Não",
      CH: "否",
      JP: "いいえ",
    },
    
  },
  PaymentConfirmation: {
    ThankYou: {
      EN: "Thank you!",
      HE: "!תודה",
      AR: "شكراً لك!",
      ES: "¡Gracias!",
      RU: "Спасибо!",
      FR: "Merci!",
      POR: "Obrigado!",
      CH: "谢谢!",
      JP: "ありがとう!",
    },
    ThePaymentWasSuccessfullyReceived: {
      EN: "The payment was successfully received",
      HE: "התשלום התקבל בהצלחה",
      AR: "تم استلام الدفعة بنجاح",
      ES: "El pago fue recibido con éxito",
      RU: "Платеж успешно получен",
      FR: "Le paiement a été reçu avec succès",
      POR: "O pagamento foi recebido com sucesso",
      CH: "付款已成功收到",
      JP: "お支払いは正常に受け取られました",
    },
    Continue: {
      EN: "Continue",
      HE: "המשך",
      AR: "استمر",
      ES: "Continuar",
      RU: "Продолжить",
      FR: "Continuer",
      POR: "Continuar",
      CH: "继续",
      JP: "続ける",
    }
  },
  CustomOrderConfirmation: {
    WeRecievedYourRequest: {
      EN: "We recieved your request!",
      HE: "!קיבלנו את הבקשה שלך",
      AR: "لقد تلقينا طلبك! ",
      ES: "¡Hemos recibido tu solicitud!",
      RU: "Мы получили ваш запрос!",
      FR: "Nous avons reçu votre demande !",
      POR: "Recebemos sua solicitação!",
      CH: "我们收到了您的请求!",
      JP: "お問い合わせを受け取りました!",
    },
  },
  CustomRequestScreen: {
    NEXT: {
      EN: "NEXT",
      HE: "הבא",
      AR: "التالي",
      ES: "SIGUIENTE",
      RU: "СЛЕДУЮЩИЙ ",
      FR: "SUIVANT",
      POR: "PRÓXIMO",
      CH: "下一个",
      JP: "次へ",
    },
    When: {
      EN: "When?",
      HE: "מתי?",
      AR: "متى؟",
      ES: "¿Cuándo?",
      RU: "Когда?",
      FR: "Quand ?",
      POR: "Quando?",
      CH: "什么时候？",
      JP: "いつ？",
    },
    Now: {
      EN: "Now",
      HE: "עכשיו",
      AR: "الآن",
      ES: "Ahora",
      RU: "Сейчас",
      FR: "Maintenant",
      POR: "Agora",
      CH: "现在",
      JP: "今",
    },
    At: {
      EN: "At",
      HE: "בשעה",
      AR: "في",
      ES: "En",
      RU: "В",
      FR: "À",
      POR: "Em",
      CH: "在",
      JP: "で",
    },
  },
  RatingIconsComp: {
    WhatAreYourThoughtsAboutThePlace: {
      EN: "What are your thoughts about the place?",
      HE: "?מה דעתך על המקום",
      AR: "ما هي أفكارك حول المكان؟",
      ES: "¿Qué piensas sobre el lugar?",
      RU: "Какие у вас мысли о месте?",
      FR: "Qu'est-ce que vous pensez de l'endroit ?",
      POR: "O que você acha do lugar?",
      CH: "你对这个地方有什么看法?",
      JP: "その場所についてどう思いますか？",
    },
  },
  NearByBottom: {
    ViewDescription: {
      EN: "View Description",
      HE: "תיאור",
      AR: "عرض الوصف",
      ES: "Ver descripción",
      RU: "Посмотреть описание",
      FR: "Voir la description",
      POR: "Ver descrição",
      CH: "查看描述",
      JP: "説明を表示する",
    },
  },
  RoomProductsScreen: {
    Request: {
      EN: "Request",
      HE: "בקשה",
      AR: "طلب",
      ES: "Solicitud",
      RU: "Запрос",
      FR: "Demande",
      POR: "Pedido",
      CH: "请求",
      JP: "要求",
    },
  },
  QuestionnaireDialog: {
    PleaseAdjustYourInterestTypesBetween: {
      EN: "Please adjust your interest types between 0-10",
      HE: "אנא התאם את תחומי העיניין שלך בין 0 ל-10",
      AR: "يرجى ضبط أنواع اهتمامك بين 0 و 10",
      ES: "Por favor, ajusta tus tipos de interés entre 0 y 10",
      RU: "Пожалуйста, укажите свои интересы в пределах от 0 до 10",
      FR: "Veuillez ajuster vos types d'intérêt entre 0 et 10",
      POR: "Por favor, ajuste seus tipos de interesse entre 0 e 10",
      CH: "请将您的兴趣类型调整在0至10之间",
      JP: "0から10の間で興味タイプを調整してください ",
    },
    WeWillSuggestYouActivitiesBasedOnYourInterests: {
      EN: "We will suggest you activities based on your interests",
      HE: "נציע לך פעילויות בהתאם לתחומי העניין שלך",
      AR: "سنقترح عليك أنشطة بناءً على اهتماماتك",
      ES: "Te sugeriremos actividades basadas en tus intereses",
      RU: "Мы предложим вам активности на основе ваших интересов",
      FR: "Nous vous suggérerons des activités en fonction de vos intérêts",
      POR: "Vamos sugerir atividades com base nos seus interesses",
      CH: "我们将根据您的兴趣为您推荐活动",
      JP: "あなたの興味に基づいて活動を提案します",
    },
  },
  FoodCartDialog: {
    YourCart: {
      EN: "Your Cart",
      HE: "העגלה שלך",
      AR: "عربة التسوق الخاصة بك",
      ES: "Tu carrito",
      RU: "Ваша корзина",
      FR: "Votre panier",
      POR: "Seu carrinho",
      CH: "您的购物车",
      JP: "あなたのカート",
    },
    TotalPrice: {
      EN: "Total Price:",
      HE: ":מחיר כולל",
      AR: "السعر الإجمالي:",
      ES: "Precio total:",
      RU: "Общая цена:",
      FR: "Prix total:",
      POR: "Preço total:",
      CH: "总价:",
      JP: "合計金額:",
    },
  },
  AddToCartDialog: {
    Price: {
      EN: "Price:",
      HE: ":מחיר",
      AR: "السعر:",
      ES: "Precio:",
      RU: "Цена:",
      FR: "Prix:",
      POR: "Preço:",
      CH: "价格:",
      JP: "価格:",
    },
    AddToCart: {
      EN: "Add to cart:",
      HE: ":הוסף לעגלה",
      AR: "أضف إلى السلة:",
      ES: "Añadir al carrito:",
      RU: "Добавить в корзину:",
      FR: "Ajouter au panier:",
      POR: "Adicionar ao carrinho:",
      CH: "添加到购物车:",
      JP: "カートに追加:",
    },
    EnterDishNotes: {
      EN: 'Enter dish notes, for example: "without egg".',
      HE: 'הכנס הערות למנה, לדוגמה: "בלי ביצה".',
      AR: 'أدخل ملاحظات الطبق، على سبيل المثال: "بدون بيضة".',
      ES: 'Ingresa notas del plato, por ejemplo: "sin huevo".',
      RU: 'Введите примечания к блюду, например: "без яйца".',
      FR: 'Entrez les notes du plat, par exemple : "sans œuf".',
      POR: 'Insira notas do prato, por exemplo: "sem ovo".',
      CH: "输入菜品备注，例如：“不加蛋”",
      JP: "料理の注意事項を入力してください。例：「卵抜き」。",
    },
  },
  FoodDescriptionDialog: {
    Description: {
      EN: "Description",
      HE: "תיאור",
      AR: "الوصف",
      ES: "Descripción",
      RU: "Описание",
      FR: "Description",
      POR: "Descrição",
      CH: "描述",
      JP: "説明",
    },
    Allergies: {
      EN: "Allergies",
      HE: "אלרגיות",
      AR: "حساسية",
      ES: "Alergias",
      RU: "Аллергии",
      FR: "Allergies",
      POR: "Alergias",
      CH: "过敏",
      JP: "アレルギー",
    },
    PossibleChanges: {
      EN: "Possible Changes",
      HE: "שינויים אפשריים",
      AR: "تغييرات ممكنة",
      ES: "Cambios Posibles",
      RU: "Возможные изменения",
      FR: "Changements Possibles",
      POR: "Alterações Possíveis",
      CH: "可能的变更",
      JP: "可能な変更",
    },
  },
  RoomServiceCartCard: {
    Quantity: {
      EN: "Quantity:",
      HE: ":כמות",
      AR: "الكمية:",
      ES: "Cantidad:",
      RU: "Количество:",
      FR: "Quantité:",
      POR: "Quantidade:",
      CH: "数量:",
      JP: "量:",
    },
    Price: {
      EN: "Price:",
      HE: ":מחיר",
      AR: "سعر:",
      ES: "Precio:",
      RU: "Цена:",
      FR: "Prix:",
      POR: "Preço:",
      CH: "价格:",
      JP: "価格:",
    },
    Changes: {
      EN: "Changes:",
      HE: ":שינויים",
      AR: "تغييرات:",
      ES: "Cambios:",
      RU: "Изменения:",
      FR: "Changements:",
      POR: "Mudanças:",
      CH: "变更:",
      JP: "変更:",
    },
  },
  FoodCard: {
    Price: {
      EN: "Price:",
      HE: ":מחיר",
      AR: "سعر:",
      ES: "Precio:",
      RU: "Цена:",
      FR: "Prix:",
      POR: "Preço:",
      CH: "价格:",
      JP: "価格:",
    },
  },
  SpaOrder: {
    MASSAGETREATMENTS: {
      EN: "MASSAGE TREATMENTS",
      HE: "טיפולי מסאג'",
      AR: "علاجات التدليك",
      ES: "TRATAMIENTOS DE MASAJE",
      RU: "МАССАЖНЫЕ ПРОЦЕДУРЫ",
      FR: "SOINS DE MASSAGE",
      POR: "TRATAMENTOS DE MASSAGEM",
      CH: "按摩治疗",
      JP: "マッサージ治療",
    },
    NEXT: {
      EN: "NEXT",
      HE: "הבא",
      AR: "التالي",
      ES: "SIGUIENTE",
      RU: "СЛЕДУЮЩИЙ ",
      FR: "SUIVANT",
      POR: "PRÓXIMO",
      CH: "下一个",
      JP: "次へ",
    },
  },
  SpaOrderPart2: {
    Therapist1: {
      EN: "Therapist 1:",
      HE: ":מטפל/מטפלת 1",
      AR: "معالِج/معالِجة 1:",
      ES: "Terapeuta 1:",
      RU: "Терапевт 1:",
      FR: "Thérapeute 1:",
      POR: "Terapeuta 1:",
      CH: "治疗师1:",
      JP: "セラピスト1:",
    },
    Therapist2: {
      EN: "Therapist 2:",
      HE: ":מטפל/מטפלת 2",
      AR: "معالِج/معالِجة 2:",
      ES: "Terapeuta 2:",
      RU: "Терапевт 2:",
      FR: "Thérapeute 2:",
      POR: "Terapeuta 2:",
      CH: "治疗师2:",
      JP: "セラピスト2:",
    },
    Therapist: {
      EN: "Therapist:",
      HE: ":מטפל/מטפלת",
      AR: "معالِج/معالِجة:",
      ES: "Terapeuta:",
      RU: "Терапевт:",
      FR: "Thérapeute:",
      POR: "Terapeuta:",
      CH: " 治疗师:",
      JP: "セラピスト:",
    },
    Male: {
      EN: "Male",
      HE: "זכר",
      AR: "ذكر",
      ES: "Masculino",
      RU: "Мужской",
      FR: "Masculin",
      POR: "Masculino",
      CH: "男性",
      JP: "男性",
    },
    Female: {
      EN: "Female",
      HE: "נקבה",
      AR: "أنثى",
      ES: "Femenino",
      RU: "Женский",
      FR: "Féminin",
      POR: "Feminino",
      CH: "女性",
      JP: "女性",
    },
    CouplesMassage: {
      EN: "Couples Massage:",
      HE: ":מסאז' זוגי",
      AR: "مساج الأزواج:",
      ES: "Masaje para parejas:",
      RU: "Массаж для пары:",
      FR: "Massage en couple:",
      POR: "Massagem para casais:",
      CH: "夫妻按摩:",
      JP: "カップルマッサージ:",
    },
    YesPlease: {
      EN: "Yes Please:",
      HE: "כן בבקשה",
      AR: "نعم من فضلك",
      ES: "Sí, por favor",
      RU: "Да, пожалуйста",
      FR: "Oui, s'il vous plaît",
      POR: "Sim, por favor",
      CH: "是的，请",
      JP: "はい、お願いします",
    },
    SessionDuration: {
      EN: "Session Duration:",
      HE: ":משך הזמן",
      AR: "مدة الجلسة:",
      ES: "Duración de la sesión:",
      RU: "Длительность сессии:",
      FR: "Durée de la séance:",
      POR: "Duração da sessão:",
      CH: "会话时长:",
      JP: "セッションの期間:",
    },
    minutes: {
      EN: "minutes",
      HE: "דקות",
      AR: "دقائق",
      ES: "minutos",
      RU: "минуты",
      FR: "minutes",
      POR: "minutos",
      CH: "分钟",
      JP: "分",
    },
    SelectOption: {
      EN: "Select option:",
      HE: ":בחר אפשרות",
      AR: "حدد الخيار:",
      ES: "Seleccionar opción:",
      RU: "Выбрать опцию:",
      FR: "Sélectionner une option:",
      POR: "Selecionar opção:",
      CH: "选择选项:",
      JP: "オプションを選択:",
    },
    NEXT: {
      EN: "NEXT",
      HE: "הבא",
      AR: "التالي",
      ES: "SIGUIENTE",
      RU: "СЛЕДУЮЩИЙ ",
      FR: "SUIVANT",
      POR: "PRÓXIMO",
      CH: "下一个",
      JP: "次へ",
    },
  },
  // EN: "",
  //   HE: "",
  //   AR: "",
  //   ES: "",
  //   RU: "",
  //   FR: "",
  //   POR: "",
  //   CH: "",
  //   JP: "",
};
