export default Languages = {
  WelcomeScreen: {
    Start: {
      EN: "START",
      HE: "התחל",
      AR: "يبدأ",
      ES: "Comenzar",
      RU: "Начинать",
      FR: "Commencer",
      POR: "Começar",
      CH: "开始",
      JP: "始める",
    },
  },
  LoginScreen: {
    Welcome: {
      EN: "Welcome!",
      HE: "ברוכים הבאים!",
      AR: "اهلا وسهلا!",
      ES: "¡Bienvenido!",
      RU: "Добро пожаловать!",
      FR: "Accueillir!",
      POR: "Bem-vindo!",
      CH: "欢迎！",
      JP: "いらっしゃいませ！",
    },
    EnterYourEmailAndPassword: {
      EN: "Enter your email & password",
      HE: "הזן את האימייל והסיסמה שלך",
      AR: "أدخل بريدك الإلكتروني وكلمة المرور",
      ES: "Ingrese su correo electrónico y contraseña",
      RU: "Введите адрес электронной почты и пароль",
      FR: "Entrez votre e-mail et votre mot de passe",
      POR: "Digite seu e-mail e senha",
      CH: "输入您的电子邮件和密码",
      JP: "メールアドレスとパスワードを入力してください",
    },
    Email: {
      EN: "Email",
      HE: "דואר אלקטרוני",
      AR: "بريد إلكتروني",
      ES: "Correo electrónico",
      RU: "Электронная почта",
      FR: "E-mail",
      POR: "E-mail",
      CH: "电子邮件",
      JP: "Eメール",
    },
    Password: {
      EN: "Password",
      HE: "סיסמה",
      AR: "كلمة المرور",
      ES: "contraseña",
      RU: "пароль",
      FR: "mot de passe",
      POR: "senha",
      CH: "密码",
      JP: "パスワード",
    },
    Login: {
      EN: "Login",
      HE: "התחבר",
      AR: "تسجيل الدخول",
      ES: "acceso",
      RU: "авторизоваться",
      FR: "connexion",
      POR: "Conecte-se",
      CH: "登录",
      JP: "ログイン",
    },
    ForgotYourPassword: {
      EN: "Forgot your password?",
      HE: "שכחת את הסיסמה?",
      AR: "نسيت كلمة السر؟",
      ES: "¿Olvidaste tu contraseña?",
      RU: "Забыли пароль?",
      FR: "Mot de passe oublié?",
      POR: "Esqueceu sua senha?",
      CH: "忘记密码了吗？",
      JP: "パスワードをお忘れですか？",
    },
    OrCreateAnewAccount: {
      EN: "Or create a new account",
      HE: "או צור חשבון חדש",
      AR: "أو إنشاء حساب جديد",
      ES: "O crea una cuenta nueva",
      RU: "Или создайте новую учетную запись",
      FR: "Ou créer un nouveau compte",
      POR: "Ou crie uma nova conta",
      CH: "或创建一个新帐户",
      JP: "または、新しいアカウントを作成します",
    },
  },
  VerificationCodeComp: {
    EnterConfirmationCode: {
      EN: "Enter Confirmation Code",
      HE: "הכנס קוד אישור",
      AR: "أدخل رمز التأكيد",
      ES: "Introducir el código de confirmación",
      RU: "Введите код подтверждения",
      FR: "Entrez le code de confirmation",
      POR: "Introduza o código de confirmação",
      CH: "输入验证码",
      JP: "認証コードを入力",
    },
    A4DigitCodeWasSentTo: {
      EN: "A 4 Digit Code Was Sent To",
      HE: "קוד בן 4 ספרות נשלח אל",
      AR: "تم إرسال رمز مكون من 4 أرقام إلى",
      ES: "Se ha enviado un código de 4 dígitos a",
      RU: "Четырехзначный код был отправлен на",
      FR: "Un code à 4 chiffres a été envoyé à",
      POR: "Um código de 4 dígitos foi enviado para",
      CH: "一个 4 位数的代码已发送至",
      JP: "4桁のコードが送信されました",
    },
    ResendCode: {
      EN: "Resend code",
      HE: "שלח קוד שוב",
      AR: "أعد إرسال الرمز",
      ES: "Reenviar codigo",
      RU: "Отправить код еще раз",
      FR: "Renvoyer le code",
      POR: "Reenviar código",
      CH: "重新发送验证码",
      JP: "コードを再送する",
    },
    Continue: {
      EN: "Continue",
      HE: "המשך",
      AR: "استمر",
      ES: "Continuar",
      RU: "Продолжить",
      FR: "Continuer",
      POR: "Continuar",
      CH: "继续",
      JP: "続ける",
    },
  },
  ResetPasswordComp: {
    PasswordReset: {
      EN: "Password Reset",
      HE: "איפוס סיסמה",
      AR: "إعادة تعيين كلمة المرور",
      ES: "Restablecimiento de contraseña",
      RU: "Восстановление пароля",
      FR: "Réinitialisation du mot de passe",
      POR: "Redefinição de senha",
      CH: "重设密码",
      JP: "パスワードのリセット",
    },
    ChooseNewPassword: {
      EN: "Choose A New Password",
      HE: "בחר סיסמא חדשה",
      AR: "اختر كلمة مرور جديدة",
      ES: "Elija una Nueva Contraseña",
      RU: "Выберите новый пароль",
      FR: "Choisissez un nouveau mot de passe",
      POR: "Escolha uma nova senha",
      CH: "选择一个新密码",
      JP: "新しいパスワードを選択してください",
    },
    NewPassword: {
      EN: "New Password",
      HE: "סיסמא חדשה",
      AR: "كلمة مرور جديدة",
      ES: "Nueva Contraseña",
      RU: "Новый пароль",
      FR: "Nouveau mot de passe",
      POR: "Nova senha",
      CH: "新密码",
      JP: "新しいパスワード",
    },
    ConfirmNewPassword: {
      EN: "Confirm New Password",
      HE: "אמת סיסמא חדשה",
      AR: "تأكيد كلمة المرور الجديدة",
      ES: "Confirmar Nueva Contraseña",
      RU: "Подтвердите новый пароль",
      FR: "Confirmer le Nouveau Mot de Passe",
      POR: "Confirmar Nova Senha",
      CH: "确认新密码",
      JP: "新しいパスワードの確認",
    },
    Continue: {
      EN: "Continue",
      HE: "המשך",
      AR: "استمر",
      ES: "Continuar",
      RU: "Продолжить",
      FR: "Continuer",
      POR: "Continuar",
      CH: "继续",
      JP: "続ける",
    },
    PasswordsDoNotMatch: {
      EN: "Passwords do not match",
      HE: "סיסמאות לא תואמות",
      AR: "كلمات المرور غير متطابقة",
      ES: "Las contraseñas no coinciden",
      RU: "Пароли не совпадают",
      FR: "Les mots de passe ne correspondent pas",
      POR: "As senhas não coincidem",
      CH: "密码不一致",
      JP: "パスワードが一致しません",
    },
  },
  GetEmailComp: {
    EmailVerification: {
      EN: "Email Verification",
      HE: 'אימות הדוא"ל',
      AR: "تأكيد بواسطة البريد الالكتروني",
      ES: "verificacion de email",
      RU: "Подтверждение по элетронной почте",
      FR: "vérification de l'E-mail",
      POR: "verificação de e-mail",
      CH: "电子邮件验证",
      JP: "メール認証",
    },
    EnterYourEmail: {
      EN: "Enter your email address",
      HE: 'הזן את כתובת הדוא"ל שלך',
      AR: "أدخل عنوان بريدك الالكتروني",
      ES: "Ingrese su dirección de correo electrónico",
      RU: "Введите ваш адрес электронной почты",
      FR: "Entrez votre adresse email",
      POR: "Insira o seu endereço de email",
      CH: "输入你的电子邮箱地址",
      JP: "メールアドレスを入力してください",
    },
    Email: {
      EN: "Email",
      HE: "דואר אלקטרוני",
      AR: "بريد إلكتروني",
      ES: "Correo electrónico",
      RU: "Электронная почта",
      FR: "E-mail",
      POR: "E-mail",
      CH: "电子邮件",
      JP: "Eメール",
    },
    Continue: {
      EN: "Continue",
      HE: "המשך",
      AR: "استمر",
      ES: "Continuar",
      RU: "Продолжить",
      FR: "Continuer",
      POR: "Continuar",
      CH: "继续",
      JP: "続ける",
    },
  },
  CreateUserScreen: {
    CreateAccount: {
      EN: "Create Account",
      HE: "צור חשבון",
      AR: "إنشاء حساب",
      ES: "Crear una cuenta",
      RU: "Зарегистрироваться",
      FR: "Créer un compte",
      POR: "Criar uma conta",
      CH: "创建账户",
      JP: "アカウントを作成する",
    },
    Email: {
      EN: "Email",
      HE: "דואר אלקטרוני",
      AR: "بريد إلكتروني",
      ES: "Correo electrónico",
      RU: "Электронная почта",
      FR: "E-mail",
      POR: "E-mail",
      CH: "电子邮件",
      JP: "Eメール",
    },
    NewPassword: {
      EN: "New Password",
      HE: "סיסמא חדשה",
      AR: "كلمة مرور جديدة",
      ES: "Nueva Contraseña",
      RU: "Новый пароль",
      FR: "Nouveau mot de passe",
      POR: "Nova senha",
      CH: "新密码",
      JP: "新しいパスワード",
    },
    ConfirmNewPassword: {
      EN: "Confirm New Password",
      HE: "אמת סיסמא חדשה",
      AR: "تأكيد كلمة المرور الجديدة",
      ES: "Confirmar Nueva Contraseña",
      RU: "Подтвердите новый пароль",
      FR: "Confirmer le Nouveau Mot de Passe",
      POR: "Confirmar Nova Senha",
      CH: "确认新密码",
      JP: "新しいパスワードの確認",
    },
    SelectLanguage: {
      EN: "Select Language",
      HE: "בחר שפה",
      AR: "اختار اللغة",
      ES: "seleccione el idioma",
      RU: "выберите язык",
      FR: "Choisir la langue",
      POR: "selecione o idioma",
      CH: "选择语言",
      JP: "言語を選択する",
    },
  },
  GetPersonalInfoComp: {
    CreateAccount: {
      EN: "Create Account",
      HE: "צור חשבון",
      AR: "إنشاء حساب",
      ES: "Crear una cuenta",
      RU: "Зарегистрироваться",
      FR: "Créer un compte",
      POR: "Criar uma conta",
      CH: "创建账户",
      JP: "アカウントを作成する",
    },
    PersonalInfo: {
      EN: "Personal Info",
      HE: "פרטים אישיים",
      AR: "معلومات شخصية",
      ES: "Información Personal",
      RU: "Личная информация",
      FR: "Informations personnelles",
      POR: "Informações pessoais",
      CH: "个人信息",
      JP: "個人情報",
    },
    FirstName: {
      EN: "First Name",
      HE: "שם פרטי",
      AR: "الاسم الأول",
      ES: "Nombre",
      RU: "Имя",
      FR: "Prénom",
      POR: "Primeiro nome",
      CH: "名字",
      JP: "名",
    },
    LastName: {
      EN: "Last Name",
      HE: "שם משפחה",
      AR: "الاسم الأخير",
      ES: "Apellido",
      RU: "Фамилия",
      FR: "Nom de famille",
      POR: "Sobrenome",
      CH: "姓氏",
      JP: "姓",
    },
    PhoneNumber: {
      EN: "Phone Number",
      HE: "מספר טלפון",
      AR: "رقم الهاتف",
      ES: "Número de teléfono",
      RU: "Номер телефона",
      FR: "Numéro de téléphone",
      POR: "Número de telefone",
      CH: "电话号码",
      JP: "電話番号",
    },
    BirthDate: {
      EN: "Birthday",
      HE: "תאריך לידה",
      AR: "عيد ميلاد",
      ES: "Cumpleaños",
      RU: "День рождения",
      FR: "Anniversaire",
      POR: "Aniversário",
      CH: "出生日期",
      JP: "誕生日",
    },
    Gender: {
      EN: "Gender",
      HE: "מגדר",
      AR: "الجنس",
      ES: "Género",
      RU: "Пол",
      FR: "Genre",
      POR: "Gênero",
      CH: "性别",
      JP: "性別",
    },
    Male: {
      EN: "Male",
      HE: "זכר",
      AR: "ذكر",
      ES: "Masculino",
      RU: "Мужской",
      FR: "Masculin",
      POR: "Masculino",
      CH: "男性",
      JP: "男性",
    },
    Female: {
      EN: "Female",
      HE: "נקבה",
      AR: "أنثى",
      ES: "Femenino",
      RU: "Женский",
      FR: "Féminin",
      POR: "Feminino",
      CH: "女性",
      JP: "女性",
    },
    Continue: {
      EN: "Continue",
      HE: "המשך",
      AR: "استمر",
      ES: "Continuar",
      RU: "Продолжить",
      FR: "Continuer",
      POR: "Continuar",
      CH: "继续",
      JP: "続ける",
    },
  },
  GetLoginInfoComp: {
    CreateAccount: {
      EN: "Create Account",
      HE: "צור חשבון",
      AR: "إنشاء حساب",
      ES: "Crear una cuenta",
      RU: "Зарегистрироваться",
      FR: "Créer un compte",
      POR: "Criar uma conta",
      CH: "创建账户",
      JP: "アカウントを作成する",
    },
    LoginInformation: {
      EN: "Login Information",
      HE: "פרטי כניסה",
      AR: "معلومات الدخول",
      ES: "Información de Inicio de Sesión",
      RU: "Информация для входа",
      FR: "Informations de Connexion",
      POR: "Informações de Login",
      CH: "登录信息",
      JP: "ログイン情報",
    },
    Email: {
      EN: "Email",
      HE: "דואר אלקטרוני",
      AR: "بريد إلكتروني",
      ES: "Correo electrónico",
      RU: "Электронная почта",
      FR: "E-mail",
      POR: "E-mail",
      CH: "电子邮件",
      JP: "Eメール",
    },
    NewPassword: {
      EN: "New Password",
      HE: "סיסמא חדשה",
      AR: "كلمة مرور جديدة",
      ES: "Nueva Contraseña",
      RU: "Новый пароль",
      FR: "Nouveau mot de passe",
      POR: "Nova senha",
      CH: "新密码",
      JP: "新しいパスワード",
    },
    ConfirmNewPassword: {
      EN: "Confirm New Password",
      HE: "אמת סיסמא חדשה",
      AR: "تأكيد كلمة المرور الجديدة",
      ES: "Confirmar Nueva Contraseña",
      RU: "Подтвердите новый пароль",
      FR: "Confirmer le Nouveau Mot de Passe",
      POR: "Confirmar Nova Senha",
      CH: "确认新密码",
      JP: "新しいパスワードの確認",
    },
    PasswordsDoNotMatch: {
      EN: "Passwords do not match",
      HE: "סיסמאות לא תואמות",
      AR: "كلمات المرور غير متطابقة",
      ES: "Las contraseñas no coinciden",
      RU: "Пароли не совпадают",
      FR: "Les mots de passe ne correspondent pas",
      POR: "As senhas não coincidem",
      CH: "密码不一致",
      JP: "パスワードが一致しません",
    },
  },
  PersonalPageScreen: {
    MyPage: {
      EN: "My page",
      HE: "העמוד שלי",
      AR: "صفحتي",
      ES: "Mi página",
      RU: "Моя страницаа",
      FR: "Ma page",
      POR: "Minha página",
      CH: "我的页面",
      JP: "マイページ",
    },
    CheckIn: {
      EN: "Check-In",
      HE: "צ'ק אין",
      AR: "تحقق في",
      ES: "Registrarse",
      RU: "Регистрироваться",
      FR: "Enregistrement",
      POR: "Check-in",
      CH: "报到",
      JP: "チェックイン",
    },
    CheckOut: {
      EN: "Check-Out",
      HE: "צ'ק אאוט",
      AR: "الدفع",
      ES: "Verificar",
      RU: "Выезд",
      FR: "Vérifier",
      POR: "Confira",
      CH: "查看",
      JP: "チェックアウト",
    },
    HouseHold: {
      EN: "Household",
      HE: "משק בית",
      AR: "أُسرَة",
      ES: "Familiar",
      RU: "Семья",
      FR: "Ménage",
      POR: "Doméstico",
      CH: "家庭",
      JP: "家庭",
    },
    RoomCleaningSchedule: {
      EN: "Room cleaning schedule",
      HE: "לוח זמנים לניקיון חדרים",
      AR: "جدول تنظيف الغرفة",
      ES: "Horario de limpieza de habitaciones",
      RU: "График уборки номера",
      FR: "Horaire de nettoyage des chambres",
      POR: "Horário de limpeza do quarto",
      CH: "房间清洁时间表",
      JP: "ルームクリーニングスケジュール",
    },
    NewRequest: {
      EN: "New Request",
      HE: "בקשה חדשה",
      AR: "طلب جديد",
      ES: "Nueva solicitud",
      RU: "Новый запрос",
      FR: "Nouvelle requête",
      POR: "Novo pedido",
      CH: "新请求",
      JP: "新しいリクエスト",
    },
  },
  SpaTreatmenScreen: {
    MassageTreatments: {
      EN: "MASSAGE TREATMENTS",
      HE: "טיפולי ספא",
      AR: "علاجات التدليك",
      ES: "TRATAMIENTOS DE MASAJE",
      RU: "МАССАЖНЫЕ ПРОЦЕДУРЫ",
      FR: "SOINS DE MASSAGE",
      POR: "TRATAMENTOS DE MASSAGEM",
      CH: "按摩护理",
      JP: "マッサージトリートメント",
    },
    TypeHere: {
      EN: "Type here",
      HE: "הקלד פה",
      AR: "أكتب هنا",
      ES: "Escriba aquí",
      RU: "Введите здесь",
      FR: "Écrivez ici",
      POR: "Digite aqui",
      CH: "在此输入",
      JP: "ここに入力",
    },
    SwedishMassage: {
      EN: "Swedish Massage",
      HE: "עיסוי שוודי",
      AR: "التدليك السويدية",
      ES: "Masaje sueco",
      RU: "Шведский массаж",
      FR: "Massage Suédois",
      POR: "Massagem sueca",
      CH: "瑞典式按摩",
      JP: "スウェディッシュマッサージ",
    },
    HotStoneMassage: {
      EN: "Hot Stone Massage",
      HE: "עיסוי אבנים חמות",
      AR: "تدليك الحجر الساخن",
      ES: "Masaje con piedras calientes",
      RU: "Массаж горячими камнями",
      FR: "Massage aux pierres chaudes",
      POR: "Massagem com pedras quentes",
      CH: "热石按摩",
      JP: "ホットストーンマッサージ",
    },
    CombinedMassage: {
      EN: "Combined Massage",
      HE: "עיסוי משולב",
      AR: "التدليك المشترك",
      ES: "Masaje Combinado",
      RU: "Комбинированный массаж",
      FR: "Massage Combiné",
      POR: "Massagem Combinada",
      CH: "组合按摩",
      JP: "複合マッサージ",
    },
    DeepTissuMassage: {
      EN: "Deep Tissue Massage",
      HE: "עיסוי רקמות עמוק",
      AR: "تدليك الأنسجة العميقة",
      ES: "Masaje de tejido profundo",
      RU: "Глубокий массаж тканей",
      FR: "Massage des tissus profonds",
      POR: "Massagem de tecidos profundos",
      CH: "深层组织按摩",
      JP: "ディープティッシュマッサージ",
    },
    PrenatalMassage: {
      EN: "Prenatal Massage",
      HE: "עיסוי טרום לידה",
      AR: "تدليك ما قبل الولادة",
      ES: "Masaje Prenatal",
      RU: "пренатальный массаж",
      FR: "Massage prénatal",
      POR: "Massagem pré-natal",
      CH: "产前按摩",
      JP: "産前マッサージ",
    },
  },
  CardScreen: {
    Description: {
      EN: "Description:",
      HE: ":תיאור",
      AR: ":وصف",
      ES: "Descripción:",
      RU: "Описание:",
      FR: "Description:",
      POR: "Descrição:",
      CH: "描述:",
      JP: "説明:",
    },
    OpeningHours: {
      EN: "Opening Hours:",
      HE: ":שעות פתיחה",
      AR: ":ساعات العمل",
      ES: "Horario de apertura:",
      RU: "Часы работы:",
      FR: "Horaires d'ouvertures:",
      POR: "Horário de Funcionamento:",
      CH: "营业时间:",
      JP: "営業時間:",
    },
    Rating: {
      EN: "Rating",
      HE: "דירוג",
      AR: "تقييم",
      ES: "Valoración",
      RU: "Рейтинг",
      FR: "Évaluation",
      POR: "Avaliação",
      CH: "评级",
      JP: "評価",
    },
    Address: {
      EN: "Address:",
      HE: ":כתובת",
      AR: ":عنوان",
      ES: "DIRECCIÓN:",
      RU: "Адрес:",
      FR: "Adresse:",
      POR: "Endereço:",
      CH: "地址:",
      JP: "住所:",
    },
    Phone: {
      EN: "Phone:",
      HE: ":טלפון",
      AR: ":هاتف",
      ES: "Teléfono:",
      RU: "Телефон:",
      FR: "Téléphone:",
      POR: "Telefone:",
      CH: "电话:",
      JP: "電話:",
    },
  },
  ConciergeActivitiesScreen: {
    RecommendedActivitiesInTheArea: {
      EN: "Recommended activities in the area",
      HE: "מקומות מומלצים באזור",
      AR: "الأنشطة الموصى بها في المنطقة",
      ES: "Actividades recomendadas en la zona",
      RU: "Рекомендуемые мероприятия в этом районе",
      FR: "Activités recommandées dans la région",
      POR: "Atividades recomendadas na área",
      CH: "该地区的推荐活动",
      JP: "周辺のおすすめアクティビティ",
    },
  },
  ConciergeMainScreen: {
    QuestionnaireRecommendations: {
      EN: "Questionnaire recommendations",
      HE: "שאלון המלצות",
      AR: "توصيات الاستبيان",
      ES: "Recomendaciones del cuestionario",
      RU: "Рекомендации по анкете",
      FR: "Recommandations du questionnaire",
      POR: "Recomendações do questionário",
      CH: "问卷建议",
      JP: "アンケートの推奨事項",
    },
    TopRatedActivities: {
      EN: "Top Rated Activities",
      HE: "פעילויות בעלות הדירוג הגבוה ביותר",
      AR: "أفضل الأنشطة تقييمًا",
      ES: "Actividades mejor valoradas",
      RU: "Лучшие оцененные мероприятия",
      FR: "Activités les mieux notées",
      POR: "Atividades mais bem avaliadas",
      CH: "最受欢迎的活动",
      JP: "トップ評価のアクティビティ",
    },
    Questionnaire: {
      EN: "Questionnaire",
      HE: "שאלון",
      AR: "استبيان",
      ES: "Cuestionario",
      RU: "Опросник",
      FR: "Questionnaire",
      POR: "Questionário",
      CH: "问卷",
      JP: "アンケート",
    },
    More: {
      EN: "More",
      HE: "לעוד",
      AR: "أكثر",
      ES: "Más",
      RU: "Более",
      FR: "Plus",
      POR: "Mais",
      CH: "更多的",
      JP: "もっと",
    },
    WithoutLeavingTheHotel: {
      EN: "Without leaving the hotel",
      HE: "בלי לצאת מהמלון",
      AR: "بدون مغادرة الفندق",
      ES: "Sin salir del hotel",
      RU: "Не выходя из отеля",
      FR: "Sans quitter l'hôtel",
      POR: "Sem sair do hotel",
      CH: "无需离开酒店",
      JP: "ホテルを出ることなく",
    },
    RecommendedPlacesToVisit: {
      EN: "Recommended places to visit",
      HE: "מקומות מומלצים לביקור",
      AR: "الأماكن الموصى بها للزيارة",
      ES: "Lugares recomendados para visitar",
      RU: "Рекомендуемые места для посещения",
      FR: "Endroits recommandés à visiter",
      POR: "Lugares recomendados para visitar",
      CH: "推荐景点",
      JP: "おすすめスポット",
    },
  },
  FeedbackScreen: {
    Feedback: {
      EN: "Feedback",
      HE: "מָשׁוֹב",
      AR: "تعليق",
      ES: "Comentario",
      RU: "Обратная связь",
      FR: "Retour",
      POR: "Opinião",
      CH: "反馈",
      JP: "フィードバック",
    },
    DidYouEnjoyTheActivity: {
      EN: "Did you enjoy the activity?",
      HE: "?נהניתם מהפעילות",
      AR: "هل استمتعت بالنشاط؟",
      ES: "¿Te gustó la actividad?",
      RU: "Вам понравилось занятие?",
      FR: "Avez-vous apprécié l'activité?",
      POR: "Gostou da atividade?",
      CH: "你喜欢这个活动吗？",
      JP: "アクティビティは楽しかったですか？",
    },
    WasTheActivityAGoodFitForYourPersonality: {
      EN: "Was the activity a good fit for your personality?",
      HE: "?האם הפעילות התאימה לאישיותך",
      AR: "هل كان النشاط مناسبًا لشخصيتك؟",
      ES: "¿La actividad se adecuaba bien a su personalidad?",
      RU: "Соответствовала ли эта деятельность вашей личности?",
      FR: "L'activité correspondait-elle à votre personnalité?",
      POR: "A atividade foi adequada para sua personalidade?",
      CH: "该活动是否适合您的个性？",
      JP: "その活動はあなたの性格にぴったりでしたか？",
    },
    AnythingElse: {
      EN: "Anything else?",
      HE: "?עוד משהו",
      AR: "أي شيء آخر؟",
      ES: "¿Algo más?",
      RU: "Что-нибудь еще?",
      FR: "Rien d'autre?",
      POR: "Algo mais?",
      CH: "还要别的吗?",
      JP: "他に何か？",
    },
  },
  HealthDeclarationScreen: {
    HealthDeclarationForm: {
      EN: "Health declaration form",
      HE: "טופס הצהרת בריאות",
      AR: "استمارة البيان الصحي",
      ES: "Formulario de declaración de salud",
      RU: "Форма декларации здоровья",
      FR: "Formulaire de déclaration de santé",
      POR: "formulário de declaração de saúde",
      CH: "健康申报表",
      JP: "健康申告書",
    },
    DoYouHaveAnyOfTheFollowingConditions: {
      EN: "Do you have any of the following conditions?",
      HE: "?האם יש לך אחד מהתנאים הבאים",
      AR: "هل لديك أي من الشروط التالية؟",
      ES: "¿Tiene alguna de las siguientes condiciones?",
      RU: "Есть ли у вас какие-либо из следующих условий?",
      FR: "Avez-vous l'une des conditions suivantes?",
      POR: "Você tem alguma das seguintes condições?",
      CH: "您是否具备以下条件?",
      JP: "次のような条件はありませんか?",
    },
    FullName: {
      EN: "Full Name",
      HE: "שם מלא",
      AR: "الاسم الكامل",
      ES: "Nombre completo",
      RU: "Полное имя",
      FR: "Nom complet",
      POR: "Nome completo",
      CH: "全名",
      JP: "フルネーム",
    },
  },
  HomeScreen: {
    PerfectForYou: {
      EN: "Perfect for you",
      HE: "מושלם בשבילך",
      AR: "المثالي بالنسبة لك",
      ES: "Perfecto para ti",
      RU: "Идеально подходит для вас",
      FR: "Parfait pour toi",
      POR: "Perfeito para você",
      CH: "非常适合你",
      JP: "あなたにぴったり",
    },
    ToTheConcierge: {
      EN: "To the concierge",
      HE: "לקונסיירז'",
      AR: "إلى البواب",
      ES: "al conserje",
      RU: "Консьержу",
      FR: "A la conciergerie",
      POR: "Para o porteiro",
      CH: "前往礼宾部",
      JP: "コンシェルジュへ",
    },
    SpaTime: {
      EN: "Spa time",
      HE: "זמן לספא",
      AR: "وقت السبا",
      ES: "tiempo de spa",
      RU: "Спа время",
      FR: "Temps de spa",
      POR: "tempo de spa",
      CH: "水疗时间",
      JP: "スパタイム",
    },
    MoreSpaTreatments: {
      EN: "More spa treatments",
      HE: "טיפולי ספא נוספים",
      AR: "المزيد من علاجات السبا",
      ES: "Más tratamientos de spa",
      RU: "Еще спа-процедуры",
      FR: "Plus de cures thermales",
      POR: "Mais tratamentos de spa",
      CH: "更多水疗护理",
      JP: "その他のスパ トリートメント",
    },
    SomethingToSnack: {
      EN: "Something to snack",
      HE: "משהו לנשנש",
      AR: "شيء لتناول وجبة خفيفة",
      ES: "algo para picar",
      RU: "Что-нибудь перекусить",
      FR: "Quelque chose à grignoter",
      POR: "Algo para lanche",
      CH: "吃点东西",
      JP: "おやつに何か",
    },
    ToTheFullMenu: {
      EN: "To the full menu",
      HE: "לתפריט המלא",
      AR: "إلى القائمة الكاملة",
      ES: "Al menú completo",
      RU: "К полному меню",
      FR: "Vers le menu complet",
      POR: "Para o menu completo",
      CH: "查看完整菜单",
      JP: "全メニューへ",
    },
  },
  HotelActivitieScreen: {
    WithoutLeavingTheHotel: {
      EN: "Without leaving the hotel",
      HE: "בלי לצאת מהמלון",
      AR: "بدون مغادرة الفندق",
      ES: "Sin salir del hotel",
      RU: "Не выходя из отеля",
      FR: "Sans quitter l'hôtel",
      POR: "Sem sair do hotel",
      CH: "无需离开酒店",
      JP: "ホテルを出ることなく",
    },
  },
  MainScreen: {
    SomethingToSnack: {
      EN: "Something to snack",
      HE: "משהו לנשנש",
      AR: "شيء لتناول وجبة خفيفة",
      ES: "algo para picar",
      RU: "Что-нибудь перекусить",
      FR: "Quelque chose à grignoter",
      POR: "Algo para lanche",
      CH: "吃点东西",
      JP: "おやつに何か",
    },
  },
  SpaConfirmationScreen: {
    YOUR: {
      EN: "YOUR",
      HE: "שֶׁלְךָ",
      AR: "لك",
      ES: "SU",
      RU: "ТВОЙ",
      FR: "TON",
      POR: "SEU",
      CH: "你的",
      JP: "あなたの",
    },
    MASSAGE: {
      EN: "MASSAGE",
      HE: "'מסאז",
      AR: "تدليك",
      ES: "MASAJE",
      RU: "МАССАЖ",
      FR: "MASSAGE",
      POR: "MASSAGEM",
      CH: "按摩",
      JP: "マッサージ",
    },
    TREATMENT: {
      EN: "TREATMENT",
      HE: "טיפול",
      AR: "علاج",
      ES: "TRATAMIENTO",
      RU: "УХОД",
      FR: "TRAITEMENT",
      POR: "TRATAMENTO",
      CH: "治疗",
      JP: "処理",
    },
    OrderDetails: {
      EN: "Order Details",
      HE: "פרטי הזמנה",
      AR: "تفاصيل الطلب",
      ES: "Detalles del pedido",
      RU: "Информация для заказа",
      FR: "détails de la commande",
      POR: "detalhes do pedido",
      CH: "订单详细信息",
      JP: "注文詳細",
    },
    Duration: {
      EN: "Duration:",
      HE: ":משך זמן",
      AR: "المدة الزمنية:",
      ES: "Duración:",
      RU: "Продолжительность:",
      FR: "Durée:",
      POR: "Tempo de duração:",
      CH: "持续时间：",
      JP: "所要時間:",
    },
    minutes: {
      EN: "minutes",
      HE: "דקות",
      AR: "دقائق",
      ES: "minutos",
      RU: "минуты",
      FR: "minutes",
      POR: "minutos",
      CH: "分钟",
      JP: "分",
    },
  },
  SpaMainScreen: {
    Spa: {
      EN: "Spa",
      HE: "ספא",
      AR: "منتجع صحي",
      ES: "Spa",
      RU: "спа",
      FR: "Spa",
      POR: "spa",
      CH: "温泉",
      JP: "スパ",
    },
    MassageTreatments: {
      EN: "MASSAGE TREATMENTS",
      HE: "טיפולי ספא",
      AR: "علاجات التدليك",
      ES: "TRATAMIENTOS DE MASAJE",
      RU: "МАССАЖНЫЕ ПРОЦЕДУРЫ",
      FR: "SOINS DE MASSAGE",
      POR: "TRATAMENTOS DE MASSAGEM",
      CH: "按摩护理",
      JP: "マッサージトリートメント",
    },
    ForMoreTreatments: {
      EN: "For more treatments",
      HE: "לטיפולים נוספים",
      AR: "للمزيد من العلاجات",
      ES: "Para más tratamientos",
      RU: "Для большего количества процедур",
      FR: "Pour plus de traitements",
      POR: "Para mais tratamentos",
      CH: "更多治疗",
      JP: "その他の治療について",
    },
    TheSpaFacilities: {
      EN: "The spa facilities",
      HE: "מתקני הספא",
      AR: "مرافق السبا",
      ES: "las instalaciones del balneario",
      RU: "Спа-услуги",
      FR: "Les installations thermales",
      POR: "As instalações do spa",
      CH: "水疗设施",
      JP: "スパ施設",
    },
  },
  NewCheckInScreen: {
    ContactlessCheckIn: {
      EN: "Contactless Check-In",
      HE: "צ'ק אין ללא מגע",
      AR: "تسجيل الوصول بدون تلامس",
      ES: "Facturación sin contacto",
      RU: "Бесконтактная регистрация",
      FR: "Enregistrement sans contact",
      POR: "Check-in sem contato",
      CH: "非接触式登记入住",
      JP: "非接触チェックイン",
    },
    PleaseReviewYourReservation: {
      EN: "Please review your reservation",
      HE: "אנא בדוק את ההזמנה שלך",
      AR: "يرجى مراجعة الحجز الخاص بك",
      ES: "Por favor revise su reserva",
      RU: "Пожалуйста, проверьте ваше бронирование",
      FR: "Veuillez vérifier votre réservation",
      POR: "Revise sua reserva",
      CH: "请检查您的预订",
      JP: "ご予約をご確認ください",
    },
    Name: {
      EN: "Name",
      HE: "שם",
      AR: "اسم",
      ES: "Nombre",
      RU: "Имя",
      FR: "Nom",
      POR: "Nome",
      CH: "姓名",
      JP: "名前",
    },
    CheckIn: {
      EN: "Check-in",
      HE: "צ'ק אין",
      AR: "تحقق في",
      ES: "Registrarse",
      RU: "Регистрироваться",
      FR: "Регистрироваться",
      POR: "Check-in",
      CH: "报到",
      JP: "チェックイン",
    },
    CheckOut: {
      EN: "Check-out",
      HE: "צ'ק אאוט",
      AR: "الدفع",
      ES: "Verificar",
      RU: "Проверить",
      FR: "Vérifier",
      POR: "Confira",
      CH: "查看",
      JP: "チェックアウト",
    },
    EstimatedTotal: {
      EN: "Estimated Total",
      HE: 'סה"כ משוער',
      AR: "المجموع التقديري",
      ES: "Total Estimado",
      RU: "Расчетная сумма",
      FR: "Total estimé",
      POR: "Total Estimado",
      CH: "估计总数",
      JP: "推定合計",
    },
    Next: {
      EN: "Next",
      HE: "הבא",
      AR: "التالي",
      ES: "Próximo",
      RU: "Следующий",
      FR: "Suivant",
      POR: "Próximo",
      CH: "下一个",
      JP: "次",
    },
  },
  ConciergeCard: {
    Call: {
      EN: "Call",
      HE: "להתקשר",
      AR: "يتصل",
      ES: "Llamar",
      RU: "Вызов",
      FR: "Appel",
      POR: "Chamar",
      CH: "称呼",
      JP: "電話",
    },
  },
  HotelActivityCard: {
    SignMeUp: {
      EN: "Sign me up",
      HE: "רשום אותי",
      AR: "أشركني",
      ES: "Inscríbeme",
      RU: "Запишите меня",
      FR: "Enregistre-moi",
      POR: "Inscreva-me",
      CH: "注册我",
      JP: "サインアップ",
    },
  },
  HotelActivityCarouselCard: {
    SignMeUp: {
      EN: "Sign me up",
      HE: "רשום אותי",
      AR: "أشركني",
      ES: "Inscríbeme",
      RU: "Запишите меня",
      FR: "Enregistre-moi",
      POR: "Inscreva-me",
      CH: "注册我",
      JP: "サインアップ",
    },
    FREE: {
      EN: "FREE",
      HE: "חינם",
      AR: "حر",
      ES: "GRATIS",
      RU: "БЕСПЛАТНО",
      FR: "GRATUIT",
      POR: "LIVRE",
      CH: "自由的",
      JP: "無料",
    },
    // FREE: {
    //   EN: "",
    //   HE: "",
    //   AR: "",
    //   ES: "",
    //   RU: "",
    //   FR: "",
    //   POR: "",
    //   CH: "",
    //   JP: "",
    // },
  },
};