export default Languages = {
    WelcomeScreen: {
        Start: {
            EN: "START",
            HE: "התחל",
            AR: "يبدأ",
            ES: "Comenzar",
            RU: "Начинать",
            FR: "Commencer",
            POR: "Começar",
            CH: "开始",
            JP: "始める"
        },
    },
    LoginScreen: {
        Welcome: {
            EN: "Welcome!",
            HE: "ברוכים הבאים!",
            AR: "اهلا وسهلا!",
            ES: "¡Bienvenido!",
            RU: "Добро пожаловать!",
            FR: "Accueillir!",
            POR: "Bem-vindo!",
            CH: "欢迎！",
            JP: "いらっしゃいませ！"
        },
        EnterYourEmailAndPassword: {
            EN: "Enter your email & password",
            HE: "הזן את האימייל והסיסמה שלך",
            AR: "أدخل بريدك الإلكتروني وكلمة المرور",
            ES: "Ingrese su correo electrónico y contraseña",
            RU: "Введите адрес электронной почты и пароль",
            FR: "Entrez votre e-mail et votre mot de passe",
            POR: "Digite seu e-mail e senha",
            CH: "输入您的电子邮件和密码",
            JP: "メールアドレスとパスワードを入力してください"
        },
        Email: {
            EN: "Email",
            HE: "דואר אלקטרוני",
            AR: "بريد إلكتروني",
            ES: "Correo electrónico",
            RU: "Электронная почта",
            FR: "E-mail",
            POR: "E-mail",
            CH: "电子邮件",
            JP: "Eメール"
        },
        Password: {
            EN: "Password",
            HE: "סיסמה",
            AR: "كلمة المرور",
            ES: "contraseña",
            RU: "пароль",
            FR: "mot de passe",
            POR: "senha",
            CH: "密码",
            JP: "パスワード"
        },
        Login: {
            EN: "Login",
            HE: "התחבר",
            AR: "تسجيل الدخول",
            ES: "acceso",
            RU: "авторизоваться",
            FR: "connexion",
            POR: "Conecte-se",
            CH: "登录",
            JP: "ログイン"
        },
        ForgotYourPassword: {
            EN: "Forgot your password?",
            HE: "שכחת את הסיסמה?",
            AR: "نسيت كلمة السر؟",
            ES: "¿Olvidaste tu contraseña?",
            RU: "Забыли пароль?",
            FR: "Mot de passe oublié?",
            POR: "Esqueceu sua senha?",
            CH: "忘记密码了吗？",
            JP: "パスワードをお忘れですか？"
        },
        OrCreateAnewAccount: {
            EN: "Or create a new account",
            HE: "או צור חשבון חדש",
            AR: "أو إنشاء حساب جديد",
            ES: "O crea una cuenta nueva",
            RU: "Или создайте новую учетную запись",
            FR: "Ou créer un nouveau compte",
            POR: "Ou crie uma nova conta",
            CH: "或创建一个新帐户",
            JP: "または、新しいアカウントを作成します"
        }
    },
    VerificationCodeComp: {
        EnterConfirmationCode: {
            EN: "Enter Confirmation Code",
            HE: "הכנס קוד אישור",
            AR: "أدخل رمز التأكيد",
            ES: "Introducir el código de confirmación",
            RU: "Введите код подтверждения",
            FR: "Entrez le code de confirmation",
            POR: "Introduza o código de confirmação",
            CH: "输入验证码",
            JP: "認証コードを入力"
        },
        A4DigitCodeWasSentTo: {
            EN: "A 4 Digit Code Was Sent To",
            HE: "קוד בן 4 ספרות נשלח אל",
            AR: "تم إرسال رمز مكون من 4 أرقام إلى",
            ES: "Se ha enviado un código de 4 dígitos a",
            RU: "Четырехзначный код был отправлен на",
            FR: "Un code à 4 chiffres a été envoyé à",
            POR: "Um código de 4 dígitos foi enviado para",
            CH: "一个 4 位数的代码已发送至",
            JP: "4桁のコードが送信されました"
        },
        ResendCode: {
            EN: "Resend code",
            HE: "שלח קוד שוב",
            AR: "أعد إرسال الرمز",
            ES: "Reenviar codigo",
            RU: "Отправить код еще раз",
            FR: "Renvoyer le code",
            POR: "Reenviar código",
            CH: "重新发送验证码",
            JP: "コードを再送する"
        },
        Continue: {
            EN: "Continue",
            HE: "המשך",
            AR: "استمر",
            ES: "Continuar",
            RU: "Продолжить",
            FR: "Continuer",
            POR: "Continuar",
            CH: "继续",
            JP: "続ける"
        }

    },
    ResetPasswordComp: {
        PasswordReset: {
            EN: "Password Reset",
            HE: "איפוס סיסמה",
            AR: "إعادة تعيين كلمة المرور",
            ES: "Restablecimiento de contraseña",
            RU: "Восстановление пароля",
            FR: "Réinitialisation du mot de passe",
            POR: "Redefinição de senha",
            CH: "重设密码",
            JP: "パスワードのリセット"
        },
        ChooseNewPassword: {
            EN: "Choose A New Password",
            HE: "בחר סיסמא חדשה",
            AR: "اختر كلمة مرور جديدة",
            ES: "Elija una Nueva Contraseña",
            RU: "Выберите новый пароль",
            FR: "Choisissez un nouveau mot de passe",
            POR: "Escolha uma nova senha",
            CH: "选择一个新密码",
            JP: "新しいパスワードを選択してください"
        },
        NewPassword: {
            EN: "New Password",
            HE: "סיסמא חדשה",
            AR: "كلمة مرور جديدة",
            ES: "Nueva Contraseña",
            RU: "Новый пароль",
            FR: "Nouveau mot de passe",
            POR: "Nova senha",
            CH: "新密码",
            JP: "新しいパスワード"
        },
        ConfirmNewPassword: {
            EN: "Confirm New Password",
            HE: "אמת סיסמא חדשה",
            AR: "تأكيد كلمة المرور الجديدة",
            ES: "Confirmar Nueva Contraseña",
            RU: "Подтвердите новый пароль",
            FR: "Confirmer le Nouveau Mot de Passe",
            POR: "Confirmar Nova Senha",
            CH: "确认新密码",
            JP: "新しいパスワードの確認"
        },
        Continue: {
            EN: "Continue",
            HE: "המשך",
            AR: "استمر",
            ES: "Continuar",
            RU: "Продолжить",
            FR: "Continuer",
            POR: "Continuar",
            CH: "继续",
            JP: "続ける"
        },
        PasswordsDoNotMatch: {
            EN: "Passwords do not match",
            HE: "סיסמאות לא תואמות",
            AR: "كلمات المرور غير متطابقة",
            ES: "Las contraseñas no coinciden",
            RU: "Пароли не совпадают",
            FR: "Les mots de passe ne correspondent pas",
            POR: "As senhas não coincidem",
            CH: "密码不一致",
            JP: "パスワードが一致しません"
          }
    },
    GetEmailComp: {
        EmailVerification: {
            EN: "Email Verification",
            HE: "אימות הדוא\"ל",
            AR: "تأكيد بواسطة البريد الالكتروني",
            ES: "verificacion de email",
            RU: "Подтверждение по элетронной почте",
            FR: "vérification de l'E-mail",
            POR: "verificação de e-mail",
            CH: "电子邮件验证",
            JP: "メール認証"
        },
        EnterYourEmail: {
            EN: "Enter your email address",
            HE: "הזן את כתובת הדוא\"ל שלך",
            AR: "أدخل عنوان بريدك الالكتروني",
            ES: "Ingrese su dirección de correo electrónico",
            RU: "Введите ваш адрес электронной почты",
            FR: "Entrez votre adresse email",
            POR: "Insira o seu endereço de email",
            CH: "输入你的电子邮箱地址",
            JP: "メールアドレスを入力してください"
        },
        Email: {
            EN: "Email",
            HE: "דואר אלקטרוני",
            AR: "بريد إلكتروني",
            ES: "Correo electrónico",
            RU: "Электронная почта",
            FR: "E-mail",
            POR: "E-mail",
            CH: "电子邮件",
            JP: "Eメール"
        },
        Continue: {
            EN: "Continue",
            HE: "המשך",
            AR: "استمر",
            ES: "Continuar",
            RU: "Продолжить",
            FR: "Continuer",
            POR: "Continuar",
            CH: "继续",
            JP: "続ける"
        }
    },
    CreateUserScreen: {
        CreateAccount: {
            EN: "Create Account",
            HE: "צור חשבון",
            AR: "إنشاء حساب",
            ES: "Crear una cuenta",
            RU: "Зарегистрироваться",
            FR: "Créer un compte",
            POR: "Criar uma conta",
            CH: "创建账户",
            JP: "アカウントを作成する"
        },
        Email: {
            EN: "Email",
            HE: "דואר אלקטרוני",
            AR: "بريد إلكتروني",
            ES: "Correo electrónico",
            RU: "Электронная почта",
            FR: "E-mail",
            POR: "E-mail",
            CH: "电子邮件",
            JP: "Eメール"
        },
        NewPassword: {
            EN: "New Password",
            HE: "סיסמא חדשה",
            AR: "كلمة مرور جديدة",
            ES: "Nueva Contraseña",
            RU: "Новый пароль",
            FR: "Nouveau mot de passe",
            POR: "Nova senha",
            CH: "新密码",
            JP: "新しいパスワード"
        },
        ConfirmNewPassword: {
            EN: "Confirm New Password",
            HE: "אמת סיסמא חדשה",
            AR: "تأكيد كلمة المرور الجديدة",
            ES: "Confirmar Nueva Contraseña",
            RU: "Подтвердите новый пароль",
            FR: "Confirmer le Nouveau Mot de Passe",
            POR: "Confirmar Nova Senha",
            CH: "确认新密码",
            JP: "新しいパスワードの確認"
        },
        SelectLanguage:{
            EN: "Select Language",
            HE: "בחר שפה",
            AR: "اختار اللغة",
            ES: "seleccione el idioma",
            RU: "выберите язык",
            FR: "Choisir la langue",
            POR: "selecione o idioma",
            CH: "选择语言",
            JP: "言語を選択する"
        }
    },
    GetPersonalInfoComp:{
        CreateAccount: {
            EN: "Create Account",
            HE: "צור חשבון",
            AR: "إنشاء حساب",
            ES: "Crear una cuenta",
            RU: "Зарегистрироваться",
            FR: "Créer un compte",
            POR: "Criar uma conta",
            CH: "创建账户",
            JP: "アカウントを作成する"
        },
        PersonalInfo: {
            EN: "Personal Info",
            HE: "פרטים אישיים",
            AR: "معلومات شخصية",
            ES: "Información Personal",
            RU: "Личная информация",
            FR: "Informations personnelles",
            POR: "Informações pessoais",
            CH: "个人信息",
            JP: "個人情報"
          },
          FirstName:{
            EN: "First Name",
            HE: "שם פרטי",
            AR: "الاسم الأول",
            ES: "Nombre",
            RU: "Имя",
            FR: "Prénom",
            POR: "Primeiro nome",
            CH: "名字",
            JP: "名"
          },
          LastName: {
            EN: "Last Name",
            HE: "שם משפחה",
            AR: "الاسم الأخير",
            ES: "Apellido",
            RU: "Фамилия",
            FR: "Nom de famille",
            POR: "Sobrenome",
            CH: "姓氏",
            JP: "姓"
          },
          PhoneNumber: {
            EN: "Phone Number",
            HE: "מספר טלפון",
            AR: "رقم الهاتف",
            ES: "Número de teléfono",
            RU: "Номер телефона",
            FR: "Numéro de téléphone",
            POR: "Número de telefone",
            CH: "电话号码",
            JP: "電話番号"
          },
          BirthDate: {
            EN: "Birthday",
            HE: "תאריך לידה",
            AR: "عيد ميلاد",
            ES: "Cumpleaños",
            RU: "День рождения",
            FR: "Anniversaire",
            POR: "Aniversário",
            CH: "出生日期",
            JP: "誕生日"
          },
          Gender: {
            EN: "Gender",
            HE: "מגדר",
            AR: "الجنس",
            ES: "Género",
            RU: "Пол",
            FR: "Genre",
            POR: "Gênero",
            CH: "性别",
            JP: "性別"
          },
          Male: {
            EN: "Male",
            HE: "זכר",
            AR: "ذكر",
            ES: "Masculino",
            RU: "Мужской",
            FR: "Masculin",
            POR: "Masculino",
            CH: "男性",
            JP: "男性"
          },
          Female: {
            EN: "Female",
            HE: "נקבה",
            AR: "أنثى",
            ES: "Femenino",
            RU: "Женский",
            FR: "Féminin",
            POR: "Feminino",
            CH: "女性",
            JP: "女性"
          },
          Continue: {
            EN: "Continue",
            HE: "המשך",
            AR: "استمر",
            ES: "Continuar",
            RU: "Продолжить",
            FR: "Continuer",
            POR: "Continuar",
            CH: "继续",
            JP: "続ける"
        }
    },
    GetLoginInfoComp:{
        CreateAccount: {
            EN: "Create Account",
            HE: "צור חשבון",
            AR: "إنشاء حساب",
            ES: "Crear una cuenta",
            RU: "Зарегистрироваться",
            FR: "Créer un compte",
            POR: "Criar uma conta",
            CH: "创建账户",
            JP: "アカウントを作成する"
        },
        LoginInformation: {
            EN: "Login Information",
            HE: "פרטי כניסה",
            AR: "معلومات الدخول",
            ES: "Información de Inicio de Sesión",
            RU: "Информация для входа",
            FR: "Informations de Connexion",
            POR: "Informações de Login",
            CH: "登录信息",
            JP: "ログイン情報"
          },
          Email: {
            EN: "Email",
            HE: "דואר אלקטרוני",
            AR: "بريد إلكتروني",
            ES: "Correo electrónico",
            RU: "Электронная почта",
            FR: "E-mail",
            POR: "E-mail",
            CH: "电子邮件",
            JP: "Eメール"
        },
        NewPassword: {
            EN: "New Password",
            HE: "סיסמא חדשה",
            AR: "كلمة مرور جديدة",
            ES: "Nueva Contraseña",
            RU: "Новый пароль",
            FR: "Nouveau mot de passe",
            POR: "Nova senha",
            CH: "新密码",
            JP: "新しいパスワード"
        },
        ConfirmNewPassword: {
            EN: "Confirm New Password",
            HE: "אמת סיסמא חדשה",
            AR: "تأكيد كلمة المرور الجديدة",
            ES: "Confirmar Nueva Contraseña",
            RU: "Подтвердите новый пароль",
            FR: "Confirmer le Nouveau Mot de Passe",
            POR: "Confirmar Nova Senha",
            CH: "确认新密码",
            JP: "新しいパスワードの確認"
        },
        PasswordsDoNotMatch: {
            EN: "Passwords do not match",
            HE: "סיסמאות לא תואמות",
            AR: "كلمات المرور غير متطابقة",
            ES: "Las contraseñas no coinciden",
            RU: "Пароли не совпадают",
            FR: "Les mots de passe ne correspondent pas",
            POR: "As senhas não coincidem",
            CH: "密码不一致",
            JP: "パスワードが一致しません"
          }
    },
    PersonalPageScreen: {
      MyPage: {
        EN: "My page",
        HE: "העמוד שלי",
        AR: "صفحتي",
        ES: "Mi página",
        RU: "Моя страницаа",
        FR: "Ma page",
        POR: "Minha página",
        CH: "我的页面",
        JP: "マイページ",
      },
      CheckIn: {
        EN: "Check-In",
        HE: "צ'ק אין",
        AR: "تحقق في",
        ES: "Registrarse",
        RU: "Регистрироваться",
        FR: "Enregistrement",
        POR: "Check-in",
        CH: "报到",
        JP: "チェックイン",
      },
      CheckOut: {
        EN: "Check-Out",
        HE: "צ'ק אאוט",
        AR: "الدفع",
        ES: "Verificar",
        RU: "Выезд",
        FR: "Vérifier",
        POR: "Confira",
        CH: "查看",
        JP: "チェックアウト",
      },
      HouseHold: {
        EN: "Household",
        HE: "משק בית",
        AR: "أُسرَة",
        ES: "Familiar",
        RU: "Семья",
        FR: "Ménage",
        POR: "Doméstico",
        CH: "家庭",
        JP: "家庭",
      },
      RoomCleaningSchedule: {
        EN: "Room cleaning schedule",
        HE: "לוח זמנים לניקיון חדרים",
        AR: "جدول تنظيف الغرفة",
        ES: "Horario de limpieza de habitaciones",
        RU: "График уборки номера",
        FR: "Horaire de nettoyage des chambres",
        POR: "Horário de limpeza do quarto",
        CH: "房间清洁时间表",
        JP: "ルームクリーニングスケジュール",
      },
      NewRequest: {
        EN: "New Request",
        HE: "בקשה חדשה",
        AR: "طلب جديد",
        ES: "Nueva solicitud",
        RU: "Новый запрос",
        FR: "Nouvelle requête",
        POR: "Novo pedido",
        CH: "新请求",
        JP: "新しいリクエスト",
      },
    },
    SpaTreatmenScreen: {
      MassageTreatments: {
        EN: "MASSAGE TREATMENTS",
        HE: "טיפולי ספא",
        AR: "علاجات التدليك",
        ES: "TRATAMIENTOS DE MASAJE",
        RU: "МАССАЖНЫЕ ПРОЦЕДУРЫ",
        FR: "SOINS DE MASSAGE",
        POR: "TRATAMENTOS DE MASSAGEM",
        CH: "按摩护理",
        JP: "マッサージトリートメント",
      },
      TypeHere: {
        EN: "Type here",
        HE: "הקלד פה",
        AR: "أكتب هنا",
        ES: "Escriba aquí",
        RU: "Введите здесь",
        FR: "Écrivez ici",
        POR: "Digite aqui",
        CH: "在此输入",
        JP: "ここに入力",
      },
      SwedishMassage: {
        EN: "Swedish Massage",
        HE: "עיסוי שוודי",
        AR: "التدليك السويدية",
        ES: "Masaje sueco",
        RU: "Шведский массаж",
        FR: "Massage Suédois",
        POR: "Massagem sueca",
        CH: "瑞典式按摩",
        JP: "スウェディッシュマッサージ",
      },
      HotStoneMassage: {
        EN: "Hot Stone Massage",
        HE: "עיסוי אבנים חמות",
        AR: "تدليك الحجر الساخن",
        ES: "Masaje con piedras calientes",
        RU: "Массаж горячими камнями",
        FR: "Massage aux pierres chaudes",
        POR: "Massagem com pedras quentes",
        CH: "热石按摩",
        JP: "ホットストーンマッサージ",
      },
      CombinedMassage: {
        EN: "Combined Massage",
        HE: "עיסוי משולב",
        AR: "التدليك المشترك",
        ES: "Masaje Combinado",
        RU: "Комбинированный массаж",
        FR: "Massage Combiné",
        POR: "Massagem Combinada",
        CH: "组合按摩",
        JP: "複合マッサージ",
      },
      DeepTissuMassage: {
        EN: "Deep Tissue Massage",
        HE: "עיסוי רקמות עמוק",
        AR: "تدليك الأنسجة العميقة",
        ES: "Masaje de tejido profundo",
        RU: "Глубокий массаж тканей",
        FR: "Massage des tissus profonds",
        POR: "Massagem de tecidos profundos",
        CH: "深层组织按摩",
        JP: "ディープティッシュマッサージ",
      },
      PrenatalMassage: {
        EN: "Prenatal Massage",
        HE: "עיסוי טרום לידה",
        AR: "تدليك ما قبل الولادة",
        ES: "Masaje Prenatal",
        RU: "пренатальный массаж",
        FR: "Massage prénatal",
        POR: "Massagem pré-natal",
        CH: "产前按摩",
        JP: "産前マッサージ",
      },
    },
}

