//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_Update
    {
        public int placeID { get; set; }
        public string email { get; set; }
        public Nullable<bool> favorite { get; set; }
        public Nullable<double> rating { get; set; }
        public Nullable<double> matchRating { get; set; }
        public Nullable<bool> doneBefore { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual User User { get; set; }
    }
}
