//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Additional_Items_Room_Service
    {
        public long requestID { get; set; }
        public int ID { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<bool> isMarked { get; set; }
    
        public virtual Room_Service_Order Room_Service_Order { get; set; }
        public virtual Additional_Items Additional_Items { get; set; }
    }
}
