//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiRequestCount
    {
        public int ProviderId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public Nullable<int> RequestCount { get; set; }
    
        public virtual ApiProvider ApiProvider { get; set; }
    }
}
