//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckIn
    {
        public int receiptID { get; set; }
        public Nullable<int> givenKeys { get; set; }
        public byte[] IdPic { get; set; }
    
        public virtual Receipt Receipt { get; set; }
    }
}
