//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Health_Declaration
    {
        public int requestID { get; set; }
        public int participantID { get; set; }
        public string name { get; set; }
        public Nullable<bool> smoking { get; set; }
        public Nullable<bool> blood_pressure { get; set; }
        public Nullable<bool> diabetes { get; set; }
        public Nullable<bool> pregnancy { get; set; }
        public Nullable<bool> surgery { get; set; }
        public Nullable<bool> antibiotics { get; set; }
        public Nullable<bool> regular_medicat { get; set; }
    
        public virtual Spa_Order Spa_Order { get; set; }
    }
}
