//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Health_Declaration
    {
        public int requestID { get; set; }
        public int participantID { get; set; }
        public string name { get; set; }
        public Nullable<bool> Back_problems { get; set; }
        public Nullable<bool> High_low_blood_pressure { get; set; }
        public Nullable<bool> Diabetes { get; set; }
        public Nullable<bool> Pregnancy { get; set; }
        public Nullable<bool> Pain_in_any_area { get; set; }
        public Nullable<bool> Under_any_medication { get; set; }
        public Nullable<bool> Asthma { get; set; }
        public Nullable<bool> Nerve_damage { get; set; }
        public Nullable<bool> Cancer { get; set; }
        public Nullable<bool> Epilepsy { get; set; }
        public Nullable<bool> Breast_feeding { get; set; }
        public Nullable<bool> Headaches_Migraines { get; set; }
        public Nullable<bool> Other { get; set; }
        public Nullable<bool> Allergies { get; set; }
    
        public virtual Spa_Order Spa_Order { get; set; }
    }
}
