//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpaAppointment
    {
        public int AppointmentID { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string Therapy1Gender { get; set; }
        public string Therapy2Gender { get; set; }
        public int hotelID { get; set; }
        public int orderID { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual User User { get; set; }
    }
}
