//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpaSchedule
    {
        public int ScheduleID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> HotelID { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public Nullable<int> AvailableMaleTherapist { get; set; }
        public Nullable<int> AvailableFemaleTherapist { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
