//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Additional_Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Additional_Items()
        {
            this.Additional_Items_Room_Service = new HashSet<Additional_Items_Room_Service>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<bool> inStock { get; set; }
        public byte[] photo { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Additional_Items_Room_Service> Additional_Items_Room_Service { get; set; }
    }
}
