//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food_And_Drinks_Room_Service
    {
        public int requestID { get; set; }
        public int ID { get; set; }
        public Nullable<int> amount { get; set; }
        public string changes { get; set; }
    
        public virtual Food_And_Drinks Food_And_Drinks { get; set; }
        public virtual Room_Service_Order Room_Service_Order { get; set; }
    }
}
