//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Free_Queue
    {
        public int roleID { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Therapist Therapist { get; set; }
    }
}
