//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Questionnaire()
        {
            this.Users = new HashSet<User>();
        }
    
        public int questionnaireID { get; set; }
        public Nullable<int> Adventure_sports { get; set; }
        public Nullable<int> nature { get; set; }
        public Nullable<int> culture { get; set; }
        public Nullable<int> concerts { get; set; }
        public Nullable<int> nightlife { get; set; }
        public Nullable<int> art { get; set; }
        public Nullable<int> personal_development { get; set; }
        public Nullable<int> sports { get; set; }
        public Nullable<int> tours { get; set; }
        public Nullable<int> shopping { get; set; }
        public Nullable<int> workshops { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
