//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int receiptID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> hour { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
        public string paymentMethod { get; set; }
        public Nullable<int> orderID { get; set; }
    
        public virtual CheckIn CheckIn { get; set; }
        public virtual Checkout Checkout { get; set; }
        public virtual Order Order { get; set; }
    }
}
