//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spa_Order_Active
    {
        public int therapyID { get; set; }
        public int roomID { get; set; }
        public int roleID { get; set; }
        public int requestID { get; set; }
    
        public virtual Spa_Order Spa_Order { get; set; }
        public virtual Therapist Therapist { get; set; }
        public virtual Therapy Therapy { get; set; }
        public virtual Therapy_Room Therapy_Room { get; set; }
    }
}
