//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Therapy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Therapy()
        {
            this.Spa_Order_Active = new HashSet<Spa_Order_Active>();
            this.Therapist_IN_Therapy = new HashSet<Therapist_IN_Therapy>();
            this.Therapy_Knowledge = new HashSet<Therapy_Knowledge>();
            this.Therapy_Room = new HashSet<Therapy_Room>();
        }
    
        public int therapyID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> minDuration { get; set; }
        public Nullable<double> basePrice { get; set; }
        public Nullable<double> priceForAdditional15 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spa_Order_Active> Spa_Order_Active { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Therapist_IN_Therapy> Therapist_IN_Therapy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Therapy_Knowledge> Therapy_Knowledge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Therapy_Room> Therapy_Room { get; set; }
    }
}
